// Interface copy, English and Swedish. Board content (day names, NOW/NU) lives in
// content.js because it is drawn on flaps, not in the page.

export const STR = {
  en: {
    edit: 'Edit', fullscreen: 'Fullscreen', exitFs: 'Exit fullscreen', sound: 'Sound', on: 'On', off: 'Off', share: 'Share', done: 'Done',
    pages: 'Pages', board: 'Board', boards: 'Boards', cue: 'This board is yours. Press Edit to make it say anything.', gotIt: 'Got it',
    shareTitle: 'Open this board on another screen', shareBody: 'The link carries the whole board. Nothing is stored on a server.', copy: 'Copy link', copied: 'Copied',
    shareLong: 'This board is too big for a QR (Quick Response) code. The link still works.',
    newBoard: 'New board', addPage: 'Add page', layout: 'Layout', channel: 'Channel', window: 'Only show at certain times',
    size: 'Grid size', custom: 'Custom', fill: 'Fill screen', rows: 'Rows', cols: 'Columns', theme: 'Theme', transition: 'Transition', speed: 'Speed',
    quiet: 'Quiet hours', quietBlank: 'Blank', quietDim: 'Dim', to: 'to', saved: 'Saved automatically in this browser.',
    duplicate: 'Duplicate', exportJ: 'Export JSON', importJ: 'Import JSON', del: 'Delete', name: 'Name',
    offline: n => `Live data ${n} min old`,
    clear: 'Clear', center: 'Centre rows', flaps: 'flaps used', full: 'The board is full. Delete something to make room.',
    blankNote: ch => `“${ch}” is not on the flaps, so it shows as blank.`,
    station: 'Station', city: 'City', label: 'Label', date: 'Date', format: 'Format', text: 'Ticker text',
    quoteNote: 'Rotates through a short set of proverbs every minute.', editing: 'Editing', playlist: 'Playlist',
    newPage: 'New page', page: 'Page', typeHere: 'TYPE HERE', copySuffix: ' copy', searching: 'Searching', noMatch: 'No match',
    modes: 'Show', eta: 'Times', etaMin: 'Minutes', etaClock: 'Clock', allDays: 'Every day',
    modeNames: { METRO: 'Metro', TRAIN: 'Train', TRAM: 'Tram', BUS: 'Bus', SHIP: 'Boat' },
    dayShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    speeds: { fast: 'Fast', gentle: 'Gentle', authentic: 'Authentic' },
    transitions: { classic: 'Classic', wave: 'Wave', drift: 'Drift', curtain: 'Curtain' },
    layouts: { full: 'Full', header: 'Header and body', split: 'Split', ticker: 'Ticker row' },
    zoneNames: { full: ['Board'], header: ['Header row', 'Body'], split: ['Left', 'Right'], ticker: ['Body', 'Ticker row'] },
    channels: { message: 'Message', clock: 'Clock and date', countdown: 'Countdown', sl: 'SL departures', weather: 'Weather', quote: 'Quotes' },
    imported: 'Board opened from a link.', importFail: 'That file is not a board.', linkFail: 'That board link is damaged or incomplete.',
    jsonNote: 'JSON means JavaScript Object Notation: a plain text copy of this board you can keep or move to another browser.',
    chip: name => `Insert ${name} chip`, typeOnBoard: 'Type on the board', duration: 'Duration in seconds',
    moveUp: 'Move up', moveDown: 'Move down', delPage: 'Delete page', lang: 'Language', controls: 'Board controls', editor: 'Editor',
    boardLink: 'Board link', fallback: 'No page is scheduled right now, so the board shows the clock.'
  },
  sv: {
    edit: 'Redigera', fullscreen: 'Helskärm', exitFs: 'Lämna helskärm', sound: 'Ljud', on: 'På', off: 'Av', share: 'Dela', done: 'Klar',
    pages: 'Sidor', board: 'Tavla', boards: 'Tavlor', cue: 'Tavlan är din. Tryck Redigera och låt den säga vad du vill.', gotIt: 'Uppfattat',
    shareTitle: 'Öppna tavlan på en annan skärm', shareBody: 'Länken bär hela tavlan. Inget sparas på någon server.', copy: 'Kopiera länk', copied: 'Kopierad',
    shareLong: 'Tavlan är för stor för en QR-kod (Quick Response). Länken fungerar ändå.',
    newBoard: 'Ny tavla', addPage: 'Lägg till sida', layout: 'Layout', channel: 'Kanal', window: 'Visa bara vissa tider',
    size: 'Rutnät', custom: 'Egen', fill: 'Fyll skärmen', rows: 'Rader', cols: 'Kolumner', theme: 'Tema', transition: 'Övergång', speed: 'Hastighet',
    quiet: 'Tysta timmar', quietBlank: 'Tom', quietDim: 'Dämpad', to: 'till', saved: 'Sparas automatiskt i den här webbläsaren.',
    duplicate: 'Duplicera', exportJ: 'Exportera JSON', importJ: 'Importera JSON', del: 'Ta bort', name: 'Namn',
    offline: n => `Livedata ${n} min gammal`,
    clear: 'Rensa', center: 'Centrera rader', flaps: 'flappar använda', full: 'Tavlan är full. Ta bort något för att få plats.',
    blankNote: ch => `“${ch}” finns inte på flapparna och visas som tomt.`,
    station: 'Station', city: 'Stad', label: 'Etikett', date: 'Datum', format: 'Format', text: 'Löptext',
    quoteNote: 'Byter bland några ordspråk varje minut.', editing: 'Redigerar', playlist: 'Spellista',
    newPage: 'Ny sida', page: 'Sida', typeHere: 'SKRIV HÄR', copySuffix: ' kopia', searching: 'Söker', noMatch: 'Ingen träff',
    modes: 'Visa', eta: 'Tider', etaMin: 'Minuter', etaClock: 'Klockslag', allDays: 'Alla dagar',
    modeNames: { METRO: 'Tunnelbana', TRAIN: 'Pendeltåg', TRAM: 'Spårvagn', BUS: 'Buss', SHIP: 'Båt' },
    dayShort: ['Sön', 'Mån', 'Tis', 'Ons', 'Tor', 'Fre', 'Lör'],
    speeds: { fast: 'Snabb', gentle: 'Lugn', authentic: 'Äkta' },
    transitions: { classic: 'Klassisk', wave: 'Våg', drift: 'Drift', curtain: 'Ridå' },
    layouts: { full: 'Hel', header: 'Rubrik och text', split: 'Delad', ticker: 'Löprad' },
    zoneNames: { full: ['Tavla'], header: ['Rubrikrad', 'Text'], split: ['Vänster', 'Höger'], ticker: ['Text', 'Löprad'] },
    channels: { message: 'Meddelande', clock: 'Klocka och datum', countdown: 'Nedräkning', sl: 'SL-avgångar', weather: 'Väder', quote: 'Citat' },
    imported: 'Tavlan öppnades från en länk.', importFail: 'Filen är inte en tavla.', linkFail: 'Tavellänken är trasig eller ofullständig.',
    jsonNote: 'JSON betyder JavaScript Object Notation: en textkopia av tavlan som du kan spara eller flytta till en annan webbläsare.',
    chip: name => `Infoga ${name} färgbricka`, typeOnBoard: 'Skriv på tavlan', duration: 'Tid i sekunder',
    moveUp: 'Flytta upp', moveDown: 'Flytta ned', delPage: 'Ta bort sida', lang: 'Språk', controls: 'Tavlans kontroller', editor: 'Redigerare',
    boardLink: 'Tavellänk', fallback: 'Ingen sida är schemalagd just nu, så tavlan visar klockan.'
  }
};
