// Interface copy, English and Swedish. Board content (day names, NOW/NU) lives in
// content.js because it is drawn on flaps, not in the page.

export const STR = {
  en: {
    // 0.10.1: one Boards list, playlists that point at boards, a board's own size, Home.
    fillNote: (r, c) => `Fill screen is worked out by the wall that shows it. Until a wall here has run it full screen, the editor shows it at ${r} × ${c}.`, fillSeen: (r, c) => `Fill screen is worked out by the wall that shows it. The editor shows it at ${r} × ${c}, the size a wall in this browser last filled.`,
    compScroll: 'The board is wider than the phone. Swipe sideways in Type mode to reach the rest.', typeOwnNew: 'Adds a message board, shown in turn with this', mixedSizes: 'Mixed sizes', boardSize: 'Size and theme', sizeOwn: 'This board keeps its own size and theme in every playlist it is in.',
    themeAll: 'Sets the theme of every board in this playlist. A board that is in other playlists changes there too.', sizeOnBoard: 'Each board has its own size now. Change it on the board.',
    deletedBoard: x => `Deleted ${x}.`, deletedIn: (x, names) => `Deleted ${x}. Also taken out of ${names.join(' and ').replace(/ and (?=.* and )/g, ', ')}.`, restored: x => `${x} is back.`,
    lastShowed: x => `Last time you showed ${x}`, lastShowedSub: 'Your account had it on a screen. Show it here too?',
    anotherOne: 'Show another board in turn', yourBoards: 'Your Boards', boardsSub: (nb, npl) => `${nb === 1 ? '1 board' : nb + ' boards'} · ${npl === 1 ? '1 playlist' : npl + ' playlists'}`,
    notHereYet2: 'On its way from your account', mTakeOut: 'Take out of this playlist', alreadyIn: 'Already in it', alreadyHere: 'Already in this playlist',
    newPlaylistName: 'New playlist', newPlaylistMade: x => `A new playlist, starting with ${x}.`, copyToNoteTpl: 'The playlist gets a copy, kept in your Boards. Changing it never changes the template.',
    inN: n => n === 1 ? 'In 1 playlist' : `In ${n} playlists`, noPlaylists: 'None yet. A playlist shows boards in turn, and starts when you add a second board to the screen.',
    previewRef: 'Shown on the big board at its own size. The playlist will show this same board.', previewCopy: 'Shown on the big board at its own size. The playlist gets a copy.',
    showBoth: 'Show both in turn', inTurnName: (a, b) => `${a} and ${b}`, nowInTurn: (a, b) => `Now showing ${a} and ${b} in turn.`,
    inPlaylists: names => names.length === 1 ? `In ${names[0]}.` : `In ${names.join(' and ').replace(/ and (?=.* and )/g, ', ')}. A change here shows in each.`, inNoPlaylist: 'Not in a playlist.',
    inThisPlaylist: x => `In ${x}`, advanced: 'Advanced', myMessage: 'My message',
    dataCounts2: (nb, mb, npl, mpl) => `${nb} of ${mb} boards, ${npl} of ${mpl} playlists`,
    homeTitle: 'Home', homeBody: 'New tiles start from these: the weather and holidays for your city, your stops, and your currency. Changing Home never changes a board you have.',
    homeStops: 'Your stops', homeCur: 'Your currency', homeScreen: city => `This screen uses ${city}.`, homeHere: 'Use Home on this screen',
    // 0.10: look, then show. Strings from the design handover (design/0.10/nav-10.js).
    secShowing: 'Showing', kindPlaylist: 'Playlist', kindBoard: 'Board', kindTemplate: 'Template',
    lookKicker: 'Previewing', showOn: 'Show on this screen', addTo: name => `Add to ${name}`,
    whereBody: 'The demo is rebuilt for your city: its weather, stops and holidays.',
    built: (city, parts) => `Built for ${city}${parts.length ? ', with ' + parts.join(', ').replace(/, ([^,]*)$/, ' and $1') : ''}.`,
    builtWeather: city => `${city} weather`, builtStops: 'the nearest stops', builtHolidays: 'its holidays',
    boardsInTurn: n => `${n} boards in turn`, editOnNow: 'Edit the board on now', editIt: 'Edit it', openPl: 'Open the playlist', holdNote: 'Edit holds the playlist on that board.',
    typeOwn: 'Type your own message', typeOwnSub: 'Opens the Welcome board with the keyboard', browse: 'Browse templates', browseSub: 'Boards that are ready to use',
    another: 'Add a board to show in turn', anotherSub: 'They take turns on the screen', thisScreen: 'This screen', putOn: 'Put this on another screen', settings: 'Settings',
    allPlaylists: n => n === 1 ? 'Your playlist' : `All your playlists (${n})`, soundOn: 'Sound on', soundOff: 'Sound off', onNowTag: 'On now',
    sNow: x => `Now showing ${x}.`, sNowKept: x => `Now showing ${x}. It is in your Boards.`, sBack: x => `Back to ${x}.`, sSaved: 'Saved', sSavedAt: t => `Saved ${t}`,
    sHold: x => `Holding on ${x} while you edit.`, sSavedBack: x => `Saved. Back to ${x}.`, showItNow: 'Show it now', sSavedShowing: x => `Saved. Showing ${x}.`,
    sTimeout: (x, back) => `Your preview of ${x} ended after 3 minutes untouched. Back to ${back}.`, sbFull: 'You have 100 playlists, the most there can be.', tplCopyNote: 'Showing a template keeps a copy in your Boards. Changing yours never changes the template.',
    // 0.7.1: My boards.
    secMyBoards: 'Boards', templatesShort: 'Templates', sections: 'Sections', signInNotFinished: 'Sign-in did not finish, so nothing changed. Try again, and finish it in this same browser.', myFull: 'Boards holds 500 boards, the most it can.', savedToMy: name => `${name} is in your Boards.`,
    bpSize: (r, c) => `Kept at ${r} × ${c}, the size it was made at. A copy fits the playlist it goes into.`, onScreen: 'On screen', bpNoTimes: 'Times are set in a playlist, since they belong to its plan.',
    searchMy: 'Search Boards', myEmptyTitle: 'Your boards to start from', myEmptyBody: 'Every board you make or take from a template is kept here.',
    browseExplore: 'Browse Explore', importShort: 'Import', allSizes: 'All sizes', showAllSizes: n => `Show all sizes (${n})`, noneThisSize: 'None at this size yet.',
    previewOnBoard: (r, c) => `Shown on the big board at this playlist's size, ${r} × ${c}.`, cutWarn: n => `${n === 1 ? '1 typed or painted flap falls' : n + ' typed or painted flaps fall'} outside at this size and will be cut.`,
    addHere: 'Add to this playlist', addedTo: (name, sb) => `${name} is added to ${sb}.`,
    fromFile: 'A file', fromVestaboard: 'A Vestaboard message', importFileNote: 'A board file goes to Boards, and a playlist file becomes a playlist with its boards.', chooseFile: 'Choose a file',
    vbNote: (r, c) => `Paste the message, one line per row. It is centred, in capitals, at ${r} × ${c}, and shown on the big board as you type.`,
    offerTitle2: (n, m) => { const a = n === 1 ? '1 playlist' : `${n} playlists`, b = m === 1 ? '1 board' : `${m} boards`; return `There ${n + m === 1 ? 'is' : 'are'} ${n && m ? `${a} and ${b}` : n ? a : b} in this browser from before you signed in.`; },
    offerKeepN: n => `Keep with my account (${n})`, vbTooMany: n => `${n === 1 ? 'The last line does' : `The last ${n} lines do`} not fit and will be left out.`,
    // 0.7: the sections, the playlist and the week. Words from GLOSSARY.md.
    secStoryboards: 'Playlists', secExplore: 'Explore', secAccount: 'Account', secSettings: 'Settings', searchLater: 'Search, coming later',
    more: 'More', mOpen: 'Open', mRename: 'Rename', mDuplicate: 'Duplicate', mSave: 'Save to Boards', mCopyTo: 'Add to a playlist', mShare: 'Share', mShareImage: 'Share as image', mExport: 'Export', mDelete: 'Delete', mDeleteAgain: 'Press again to delete',
    changedTitle: 'Some words have moved', changedBody: 'Nothing you made has changed, only what things are called.',
    changedRows: [['What was a board', 'is now a playlist'], ['What was a page', 'is now a board'], ['The playlist', "is now worked out for you, as Today's playlist"]],
    sbIntro: 'A playlist is what a screen plays: its boards in order, and when each one shows.', newStoryboard: 'New playlist', allStoryboards: 'All playlists',
    sbMeta: (size, theme, n) => `${size} · ${theme} · ${n === 1 ? '1 board' : n + ' boards'}`, nowPlays: names => `Now: ${names}`, playingHere: 'Playing on this screen', clockOnly: 'the clock',
    viewWeek: 'Week', viewBoards: 'Boards', viewDisplay: 'Display',
    anyTime: 'Any time', anyTimeNone: 'Every board has a time.', anyTimeHint: 'No time set, so it takes turns with the others whenever it can.', aloneTag: 'Alone',
    seeInWeek: 'See it in the week', whenShows: 'When it shows',
    copyToTitle: 'Add to a playlist', copyToNote: 'The playlist shows this same board, so a change to it shows in both. Duplicate it first for one of its own.', copiedTo: name => `Copied to ${name}.`, cancel: 'Cancel',
    displayNote: 'These describe the display.',
    exIntro: 'Show a template on this screen, or add one of its boards to a playlist you have. Either way you get a copy in your Boards.', importTitle: 'From a file', fromOthers: 'From other people', laterShort: 'Later',
    useAsNew: 'Use as a new playlist', addToSb: 'Add to a playlist',
    yourData: 'Your data', dataCounts: (n, max) => `${n} of ${max} playlists`, connections: 'Connections', submissions: 'Your submissions',
    todaysPlaylist: "Today's playlist", playlistFor: day => `Playlist for ${day}`, playlistNote: 'Worked out from when each board shows. Change the week to change it.',
    nowShowing: (names, until, next) => until ? `Now showing ${names} until ${until}, then ${next}` : `Now showing ${names}`,
    prevWeek: 'Previous week', nextWeek: 'Next week', weekOf: (a, b) => `${a} to ${b}`, fromYesterday: 'from yesterday', comingDates: 'Coming dates', allDay: 'all day',
    weekEmpty: 'No board has a time yet, so they all take turns all day. Drag down a day to give one a time.',
    addATime: 'Add a time', timeCardTitle: 'Which board shows then?', newBoardShort: 'New board', maxTimes: 'That board has eight times already, the most it can have.',
    edit: 'Edit', fullscreen: 'Fullscreen', exitFs: 'Exit fullscreen', sound: 'Sound', on: 'On', off: 'Off', share: 'Share', done: 'Done',
    pages: 'Boards', board: 'Board', boards: 'Boards', cue: 'This is a demo. Press Edit to make it yours.', gotIt: 'Got it',
    shareTitle: 'Put this on another screen', shareBody: 'The link carries this playlist as it is now. If you change it later, share it again.', linkCopied: 'Link copied. Open it on the other screen.', qrLarge: 'Show the QR code full size', close: 'Close', copy: 'Copy link', copied: 'Copied',
    shareLong: 'This playlist is too big for a QR (Quick Response) code. The link still works.',
    newBoard: 'New board', addPage: 'Add a board', layout: 'Layout', channel: 'Channel',
    size: 'Grid size', custom: 'Custom', fill: 'Fill screen', rows: 'Rows', cols: 'Columns', theme: 'Theme', transition: 'Transition', speed: 'Speed',
    quiet: 'Quiet hours', quietBlank: 'Blank', quietDim: 'Dim', to: 'to', saved: 'Saved automatically in this browser.',
    duplicate: 'Duplicate', exportJ: 'Export JSON', importJ: 'Import JSON', del: 'Delete', name: 'Name',
    offline: n => `Live data ${n} min old`,
    clear: 'Clear', center: 'Centre rows', flaps: 'flaps used', full: 'The zone is full. Delete something to make room.',
    blankNote: ch => `“${ch}” is not on the flaps, so it shows as blank.`,
    station: 'Station', city: 'City', label: 'Label', date: 'Date', format: 'Format', text: 'Ticker text',
    quoteNote: 'Rotates through a short set of proverbs every minute.', editing: 'Editing',
    stageRole: 'split-flap board', stageLabel: (board, n, of, name) => n ? `${board}, board ${n} of ${of}${name ? ', ' + name : ''}` : board,
    page: 'Board', recommended: 'Recommended', tplSizeOwn: 'The size this template is made for. Pick another and the preview shows it.', tplSizeOther: s => `Shown at the size you picked. The template is made for ${s}.`,
    unsetHint: { weather: 'Pick a city below. Until then the board shows WEATHER and a dash.', rotating: 'Add a message below. Until then the board shows MESSAGES and a dash.', url: 'Add a web address below. Until then the board shows FROM THE WEB and a dash.', departuresNear: 'This shows the stop nearest the screen once it has a place. Set one in Display, or pick a stop below. Until then the board says LOADING.',
      sl: 'Pick a station below. Until then the board shows SL and a dash.', headlines: 'Add a feed below. Until then the board shows HEADLINES and a dash.', worldtime: 'Add a city below. Until then the board shows WORLD CLOCK and a dash.',
      departures: 'Pick a stop below. Until then the board shows DEPARTURES and a dash.', markets: 'Pick a symbol below. Until then the board shows a dash.', rates: 'Pick a bank below. Until then the board shows RATES and a dash.' },
    compHint: 'Tap a flap, then type. This line is only in the editor.', copySuffix: ' copy', searching: 'Searching', noMatch: 'No match',
    modes: 'Show', eta: 'Times', etaMin: 'Minutes', etaClock: 'Clock', etaCycle: 'Alternate', allDays: 'Every day',
    modeNames: { METRO: 'Metro', TRAIN: 'Train', TRAM: 'Tram', BUS: 'Bus', SHIP: 'Boat' },
    dayShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    speeds: { fast: 'Fast', gentle: 'Gentle', authentic: 'Authentic' },
    transitions: { classic: 'Classic', wave: 'Wave', drift: 'Drift', curtain: 'Curtain' },
    layouts: { full: 'Full', header: 'Header and body', split: 'Split', ticker: 'Ticker row', stacked: 'Stacked' },
    zoneNames: { full: ['Whole board'], header: ['Header row', 'Body'], split: ['Left', 'Right'], ticker: ['Body', 'Ticker row'], stacked: ['Top half', 'Bottom half'] },
    channels: { message: 'Message', clock: 'Clock and date', bigclock: 'Big clock', bigtext: 'Big text', countdown: 'Countdown', sl: 'SL departures', weather: 'Weather', art: 'Colour pattern', quote: 'Quotes',
      rotating: 'Rotating messages', menu: 'Menu', wordclock: 'Word clock', today: 'Today', electricity: 'Electricity price', currency: 'Currency', onthisday: 'On this day', url: 'Follow a URL', letterclock: 'Letter clock' },
    colour: 'Colour', rainbow: 'Rainbow', themeColour: 'Theme', pattern: 'Pattern', every: 'Change every', seconds: 's',
    patterns: { rainbow: 'Rainbow', nordic: 'Nordic flags', rain: 'Rain', confetti: 'Confetti', wave: 'Wave', checker: 'Checker' },
    view: 'Show', views: { now: 'Now', hours: 'Next hours', days: 'Three days' },
    versionLog: 'Version log', back: 'Back', logNote: 'Each version is a release, newest first. The same log is on', bigTextLabel: 'Text', bigTextNote: 'Big letters are 5 flaps tall, so a 6 x 22 display fits about 5 characters at a time; longer text moves through word by word.',
    slHome: 'Follow my home station on the SL map', slHomeNone: 'Star a station on the SL map to use it here.', slHomeIs: name => `Home station: ${name}`,
    slMapLink: 'Open the SL map', slWhat: 'Any Storstockholms Lokaltrafik (SL) stop: metro, commuter train, tram, bus and boat.',
    volume: 'Volume', soundStyle: 'Flap sound', sounds: { clack: 'Clack', heavy: 'Heavy', soft: 'Soft', tick: 'Tick' }, preview: 'Preview', previewSound: 'Play sample',
    templates: 'Start from a template', useTemplate: 'Create', kioskLink: 'Link for a wall screen (kiosk mode, no controls)',
    previewing: name => name,
    imported: 'Playlist opened from a link.', importedCopy: 'Playlist opened from a link. Boards you already had with other content were kept, and the link\'s came in as copies.', importFail: 'That file is not a playlist.', linkFail: 'That playlist link is damaged or incomplete.',
    jsonNote: 'JSON means JavaScript Object Notation: a plain text copy of a playlist you can keep or move to another browser.',
    chip: name => `Insert ${name} chip`, typeOnBoard: 'Type on the board', duration: 'Duration in seconds',
    moveUp: 'Move up', moveDown: 'Move down', lang: 'Language', langHint: 'For the editor and for what boards print, like days and months. Kept in this browser.', controls: 'Controls', editor: 'Editor',
    boardLink: 'Playlist link',
    // editor drawer (DESIGN-HANDOVER-editor.md)
    addTime: 'Add another time', removeTime: 'Remove this time', rolls: 'Rolls', rollStart: 'Roll every flap when the display starts', rollHourly: 'Roll again on the hour', pageTransition: 'Transition to this board', boardDefault: name => `Playlist default (${name})`, showAlone: 'Show alone while this is on', showAloneHint: 'Boards without a time wait until it ends.', winDays: 'Days of the week', winDate: 'A date', everyYear: 'Every year',
    monthShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    accSignedOut: 'Signed out. Sign in to sync', signInToSync: 'Sign in to sync',
    accSignedOutBody: n => (n ? `You were signed out, so ${n === 1 ? 'a change here has' : n + ' playlists here have changes that have'} not reached your account yet. ` : 'You were signed out. ') + 'Your playlists are still here. Sign in again to sync them.',
    confirmSignOutUnsynced: n => `${n === 1 ? '1 playlist has changes' : n + ' playlists have changes'} that have not reached your account yet. Connect and try again, or sign out anyway and keep ${n === 1 ? 'it' : 'them'} here as a guest.`,
    signOutAnyway: 'Sign out anyway', signOutAgain: 'Press again to sign out', deleteAgain: 'Press again to delete',
    keptAsGuest: n => `Signed out. ${n === 1 ? '1 playlist with unsynced changes is' : n + ' playlists with unsynced changes are'} kept here as a guest.`,
    refusedBoard: (name, why) => `“${name}” is kept here only: ${why === 'too_many_boards' ? 'your account holds 50 playlists, the most it can.' : why === 'too_big' ? 'it is too big to store.' : 'the account could not take it.'}`,
    signIn: 'Sign in', renameBoard: 'Rename playlist',
    account: 'Account', accGuestSub: 'Guest, playlists in this browser only', changedAt: at => `Changed ${at}`, accSynced: 'Synced', accSyncedExcept: n => `Synced, except ${n === 1 ? '1 playlist' : n + ' playlists'}`, accWaiting: 'Waiting to sync', accFailed: 'Could not sync, it will try again',
    accGuestBody: 'You are using Split-Flap as a guest. Your playlists are kept in this browser only, so clearing its data or changing phone or computer loses them.',
    accSignInBody: 'Sign in with Google and your playlists are kept with your account, on any device you sign in on.', signInGoogle: 'Sign in with Google', accPrivacy: 'What an account stores',
    offerTitle: n => n === 1 ? 'There is 1 playlist in this browser from before you signed in.' : `There are ${n} playlists in this browser from before you signed in.`,
    offerBody: n => n === 1 ? 'Keep it with your account, or leave it here as it is.' : 'Untick any you want to leave here as they are. The rest go to your account.', offerKeep: 'Keep with my account', offerLeave: n => n === 1 ? 'Leave here' : 'Leave them all here',
    offerDone: (n, m = 0) => { const a = n === 1 ? '1 playlist' : `${n} playlists`, b = m === 1 ? '1 board' : `${m} boards`, both = n && m ? `${a} and ${b}` : n ? a : b; return `${both} ${n + m === 1 ? 'is' : 'are'} now in your account.`; },
    signInPrompt: safari => 'Your playlists live only in this browser. Sign in to keep them safe and on your other devices.' + (safari ? " Safari also clears a site's storage after 7 days without a visit." : ''), notNow: 'Not now',
    exportAll: 'Export my account', signOut: 'Sign out', confirmSignOut: 'Your playlists leave this browser and stay in your account.',
    deleteAccount: 'Delete account', confirmDelete: 'This deletes your account and every playlist in it, and it cannot be undone.', otherDevice: ' (copy)',
    signInFailed: 'Sign in did not start. Try again in a moment.', accountDeleted: 'Your account and its playlists are deleted.', signInAgainToDelete: 'For safety, sign in again, then delete the account.',
    deleteFailed: 'The account could not be deleted. Try again in a moment.', startGuest: 'As a guest, your playlists are kept in this browser only.', syncFailedMark: 'Could not sync',
    help: 'Help', helpSub: 'How Split-Flap works', gridIs: (r, c) => `The display is ${r} × ${c} flaps.`, changeSize: 'Change the size',
    chooseContent: 'Choose content',
    startTitle: 'Start from a template', skip: 'Keep the demo playlist',
    moveNamed: name => `Move ${name}`, reorderHint: 'Drag to reorder, or focus the handle and use the arrow keys',
    boardsCount: n => n === 1 ? '1 board' : `${n} boards`, templatesCount: n => `${n} templates`, pagesCount: n => n === 1 ? '1 board' : `${n} boards`,
    pageName: 'Board name', zones: 'Zones', tapZone: 'Tap a zone to choose what it shows.', tapZoneOne: 'Tap the zone to choose what it shows.',
    showFor: 'Show for', daysLabel: 'Days', from: 'From', saveImage: 'Save as image', less: 'Less', more1: 'More',
    change: 'Change', moreOptions: 'More options', fewer: 'Fewer options', searchContent: 'Search content',
    shapeNote: (h, w) => `Previews are drawn at the shape of this zone: ${h} × ${w} flaps.`, later: 'Arrives with the relay', noResults: 'Nothing matches. Try a shorter word.',
    remove: 'Remove', changeCity: 'Search for another city', searchCity: 'Search for a city', addStation: 'Add a station', maxStations: 'Up to six stations.',
    seeAll: n => `See all ${n}`,
    whereTitle: 'Where is this screen?', whereHint: 'The demo and every template are built for it: the weather, the nearest stop, the holidays, the currency and the clock.', notHereYet: 'Not available here yet',
    feedAdd: 'Add a feed by its address', feedBad: 'That is not a feed address this can read: it needs to start https:// on a public site.',
    feedSignedIn: 'Another feed is kept with your account under Account, and wall screens can then read it.', feedGuest: 'As a guest, another feed works only if it lets other sites read it. Sign in and any feed works, on wall screens too.',
    connDefault: { av: 'Alpha Vantage', sheet: 'My sheet', feed: 'Feed', json: 'Feed' }, connKinds: { av: 'API key', sheet: 'Sheet', feed: 'Feed', json: 'JSON' },
    connNone: 'Your own sources, such as an Alpha Vantage key or a published sheet, show here once you add one in a tile.',
    connLocal: 'Kept in this browser. Sign in to keep them with your account too.', connSynced: 'Kept with your account, and on this browser until you sign out.', connLocalOnly: 'Kept in this browser only for now.',
    connBad: 'That does not look like a key or an https link.',
    searchSymbol: 'Search for a share or an ETF', maxSymbols: 'Up to eight, taking turns.', viaLondon: 'Swedish, priced via London', typeSymbol: 'Type a symbol and press Enter',
    ownSymbolHint: 'As your source writes it: IBM or ERIC-B.STO for a key, the Symbol column for a sheet.',
    yourKey: 'Your Alpha Vantage key', yourSheet: 'Your published sheet (CSV link)',
    keyHint: 'Never in the board or its link. Kept in this browser, and with your account when you are signed in. Anyone at this screen can read it, so use a free key made for this. A free key allows 25 calls a day: the board asks once per symbol after each close.',
    sheetHint: 'Kept in this browser, and with your account when you are signed in. With a history block per symbol the line starts from the first day; without one, this screen builds it from the prices as the days go by.', getKey: 'Get a free key', sheetHow: 'How to set up the sheet',
    addStop: 'Search for a stop or station', maxStops: 'Up to four stops.', nearby: 'Near the place in Display',
    nearIs: (stop, city) => `Nearest stop to ${city}: ${stop}. Pick another below to change it.`, nearLooking: 'Looking for the nearest stop…',
    nearNeedsPlace: 'Set a place in Display and the nearest stop is picked for you, or search for one below.',
    lineTemplate: 'Line template', insert: 'Insert', firstItem: 'First item in the feed', sampleFeed: 'A sample feed, until you add an address', prints: 'The board will print',
    feedErr: 'This address could not be read. It may not allow other sites to read it.', loadingFeed: 'Fetching the feed.',
    unknownToken: k => `“${k}” is not in the feed, so it prints nothing.`,
    sunFrom: city => `Sun times for ${city}, the place in Display.`, sunNeedsLoc: 'Sun times need a place. Set one under', boardName: 'Playlist name',
    boardLoc: 'Place', locHint: 'Where this screen is. New boards start from it: the weather, the nearest stop, the holidays, the currency, and 12 or 24 hours.',
    locAgain: 'Pick the city again to add its country and time zone, so holidays and the currency follow it.',
    tzNote: (city, tz, here) => `${city} is on ${tz} and this screen's clock is on ${here}. Times in the week follow the screen's clock. Departures show the stop's own time.`,
    current: 'Current', open: 'Open', exportB: 'Export', importB: 'Import a playlist',
    undo: 'Undo', redo: 'Redo', composerMode: 'Composer mode', type: 'Type', paint: 'Paint', photo: 'Photo',
    brush: 'Brush', fillTool: 'Fill', mirror: 'Mirror', paintColour: 'Paint colour', blankChip: 'Blank',
    choosePhoto: 'Choose photo', takePhoto: 'Take photo', sampleImage: 'No photo chosen', sampleNote: 'Choose a photo or take one. The sliders then place it in the zone.',
    photoFail: 'That file could not be opened as a picture.', photoLocal: 'The photo stays in this browser. Only the flaps are saved.',
    zoom: 'Zoom', posX: 'Horizontal position', posY: 'Vertical position', dither: 'Dithering', ditherHint: 'Mixes flaps to suggest the colours in between', blankColour: 'Count blank flaps as a colour',
    today: 'Today', yesterday: 'Yesterday', drafts: 'Earlier messages', draftsNote: 'Kept in this browser. A message is kept here when you leave the composer after changing it.', noDrafts: 'Nothing yet. A message is kept here when you leave the composer after changing it.', use: 'Use',
  },
  sv: {
    // 0.10.1: en lista med tavlor, spellistor som pekar på tavlor, tavlans egen storlek, Hem.
    fillNote: (r, c) => `Fyll skärmen räknas ut av väggen som visar den. Tills en vägg här har visat den i helskärm visar redigeraren den i ${r} × ${c}.`, fillSeen: (r, c) => `Fyll skärmen räknas ut av väggen som visar den. Redigeraren visar den i ${r} × ${c}, storleken en vägg i den här webbläsaren senast fyllde.`,
    compScroll: 'Tavlan är bredare än telefonen. Svep åt sidan i läget Skriv för att nå resten.', typeOwnNew: 'Lägger till en meddelandetavla, som visas i tur med den här', mixedSizes: 'Blandade storlekar', boardSize: 'Storlek och tema', sizeOwn: 'Tavlan behåller sin storlek och sitt tema i varje spellista den finns i.',
    themeAll: 'Sätter temat för alla tavlor i spellistan. En tavla som finns i andra spellistor ändras där också.', sizeOnBoard: 'Varje tavla har sin egen storlek nu. Ändra den på tavlan.',
    deletedBoard: x => `${x} är borttagen.`, deletedIn: (x, names) => `${x} är borttagen. Den togs också ur ${names.join(' och ').replace(/ och (?=.* och )/g, ', ')}.`, restored: x => `${x} är tillbaka.`,
    lastShowed: x => `Förra gången visade du ${x}`, lastShowedSub: 'Ditt konto hade den på en skärm. Visa den här också?',
    anotherOne: 'Visa en till tavla i tur', yourBoards: 'Dina tavlor', boardsSub: (nb, npl) => `${nb === 1 ? '1 tavla' : nb + ' tavlor'} · ${npl === 1 ? '1 spellista' : npl + ' spellistor'}`,
    notHereYet2: 'På väg från ditt konto', mTakeOut: 'Ta ur spellistan', alreadyIn: 'Finns redan där', alreadyHere: 'Finns redan i spellistan',
    newPlaylistName: 'Ny spellista', newPlaylistMade: x => `En ny spellista, som börjar med ${x}.`, copyToNoteTpl: 'Spellistan får en kopia, sparad bland dina tavlor. Ändrar du den ändras aldrig mallen.',
    inN: n => n === 1 ? 'I 1 spellista' : `I ${n} spellistor`, noPlaylists: 'Inga än. En spellista visar tavlor i tur och ordning, och börjar när du lägger till en andra tavla på skärmen.',
    previewRef: 'Visas på stora tavlan i sin egen storlek. Spellistan visar samma tavla.', previewCopy: 'Visas på stora tavlan i sin egen storlek. Spellistan får en kopia.',
    showBoth: 'Visa båda i tur', inTurnName: (a, b) => `${a} och ${b}`, nowInTurn: (a, b) => `Visar nu ${a} och ${b} i tur och ordning.`,
    inPlaylists: names => names.length === 1 ? `I ${names[0]}.` : `I ${names.join(' och ').replace(/ och (?=.* och )/g, ', ')}. En ändring här syns i varje.`, inNoPlaylist: 'Inte i någon spellista.',
    inThisPlaylist: x => `I ${x}`, advanced: 'Avancerat', myMessage: 'Mitt meddelande',
    dataCounts2: (nb, mb, npl, mpl) => `${nb} av ${mb} tavlor, ${npl} av ${mpl} spellistor`,
    homeTitle: 'Hem', homeBody: 'Nya rutor börjar härifrån: väder och helgdagar för din stad, dina hållplatser och din valuta. En ändring i Hem ändrar aldrig en tavla du har.',
    homeStops: 'Dina hållplatser', homeCur: 'Din valuta', homeScreen: city => `Den här skärmen använder ${city}.`, homeHere: 'Använd Hem på den här skärmen',
    // 0.10: titta, sedan visa.
    secShowing: 'Visas', kindPlaylist: 'Spellista', kindBoard: 'Tavla', kindTemplate: 'Mall',
    lookKicker: 'Förhandsvisar', showOn: 'Visa på den här skärmen', addTo: name => `Lägg till i ${name}`,
    whereBody: 'Demon byggs om för din stad: dess väder, hållplatser och helgdagar.',
    built: (city, parts) => `Byggd för ${city}${parts.length ? ', med ' + parts.join(', ').replace(/, ([^,]*)$/, ' och $1') : ''}.`,
    builtWeather: city => `vädret i ${city}`, builtStops: 'närmaste hållplatserna', builtHolidays: 'dess helgdagar',
    boardsInTurn: n => `${n} tavlor som turas om`, editOnNow: 'Redigera tavlan som visas', editIt: 'Redigera', openPl: 'Öppna spellistan', holdNote: 'Medan du redigerar stannar spellistan på den tavlan.',
    typeOwn: 'Skriv ditt eget meddelande', typeOwnSub: 'Öppnar tavlan Välkommen med tangentbordet', browse: 'Bläddra bland mallar', browseSub: 'Tavlor som är klara att använda',
    another: 'Lägg till en tavla som turas om', anotherSub: 'De turas om på skärmen', thisScreen: 'Den här skärmen', putOn: 'Visa på en annan skärm', settings: 'Inställningar',
    allPlaylists: n => n === 1 ? 'Din spellista' : `Alla dina spellistor (${n})`, soundOn: 'Ljud på', soundOff: 'Ljud av', onNowTag: 'Visas nu',
    sNow: x => `Visar nu ${x}.`, sNowKept: x => `Visar nu ${x}. Den finns bland dina tavlor.`, sBack: x => `Tillbaka till ${x}.`, sSaved: 'Sparat', sSavedAt: t => `Sparat ${t}`,
    sHold: x => `Stannar på ${x} medan du redigerar.`, sSavedBack: x => `Sparat. Tillbaka till ${x}.`, showItNow: 'Visa den nu', sSavedShowing: x => `Sparat. Visar ${x}.`,
    sTimeout: (x, back) => `Förhandsvisningen av ${x} slutade efter 3 minuter utan att någon rörde den. Tillbaka till ${back}.`, sbFull: 'Du har 100 spellistor, så många som går.', tplCopyNote: 'När du visar en mall sparas en kopia bland dina tavlor. Ändrar du din ändras aldrig mallen.',
    // 0.7.1: Mina tavlor.
    secMyBoards: 'Tavlor', templatesShort: 'Mallar', sections: 'Sektioner', signInNotFinished: 'Inloggningen blev inte klar, så inget ändrades. Försök igen, och gör klart den i samma webbläsare.', myFull: 'Tavlor rymmer 500 tavlor, så många som går.', savedToMy: name => `${name} finns bland dina tavlor.`,
    bpSize: (r, c) => `Sparad i ${r} × ${c}, storleken den gjordes i. En kopia anpassas till spellistan den läggs i.`, onScreen: 'På skärmen', bpNoTimes: 'Tider sätts i en spellista, eftersom de hör till dess plan.',
    searchMy: 'Sök bland tavlor', myEmptyTitle: 'Dina tavlor att utgå från', myEmptyBody: 'Varje tavla du gör eller tar från en mall sparas här.',
    browseExplore: 'Titta i Utforska', importShort: 'Importera', allSizes: 'Alla storlekar', showAllSizes: n => `Visa alla storlekar (${n})`, noneThisSize: 'Inga i den här storleken än.',
    previewOnBoard: (r, c) => `Visas på den stora tavlan i spellistans storlek, ${r} × ${c}.`, cutWarn: n => `${n === 1 ? '1 skriven eller målad flapp hamnar' : n + ' skrivna eller målade flappar hamnar'} utanför i den här storleken och klipps bort.`,
    addHere: 'Lägg till i den här spellistan', addedTo: (name, sb) => `${name} är tillagd i ${sb}.`,
    fromFile: 'En fil', fromVestaboard: 'Ett Vestaboard-meddelande', importFileNote: 'En tavelfil hamnar i Tavlor, och en spellistefil blir en spellista med sina tavlor.', chooseFile: 'Välj en fil',
    vbNote: (r, c) => `Klistra in meddelandet, en rad per rad. Det centreras, med versaler, i ${r} × ${c}, och visas på den stora tavlan medan du skriver.`,
    offerTitle2: (n, m) => { const a = n === 1 ? '1 spellista' : `${n} spellistor`, b = m === 1 ? '1 tavla' : `${m} tavlor`; return `Det finns ${n && m ? `${a} och ${b}` : n ? a : b} i den här webbläsaren från innan du loggade in.`; },
    offerKeepN: n => `Spara med mitt konto (${n})`, vbTooMany: n => `${n === 1 ? 'Sista raden får' : `De sista ${n} raderna får`} inte plats och tas bort.`,
    // 0.7: sektionerna, spellistan och veckan. Orden kommer från GLOSSARY.md.
    secStoryboards: 'Spellistor', secExplore: 'Utforska', secAccount: 'Konto', secSettings: 'Inställningar', searchLater: 'Sök, kommer senare',
    more: 'Mer', mOpen: 'Öppna', mRename: 'Byt namn', mDuplicate: 'Duplicera', mSave: 'Spara i Tavlor', mCopyTo: 'Lägg till i en spellista', mShare: 'Dela', mShareImage: 'Dela som bild', mExport: 'Exportera', mDelete: 'Radera', mDeleteAgain: 'Tryck igen för att radera',
    changedTitle: 'Några ord har flyttat', changedBody: 'Inget du har gjort har ändrats, bara vad saker heter.',
    changedRows: [['Det som var en tavla', 'är nu en spellista'], ['Det som var en sida', 'är nu en tavla'], ['Spellistan', 'räknas nu ut åt dig, som Dagens spellista']],
    sbIntro: 'En spellista är det en skärm spelar: dess tavlor i ordning, och när var och en visas.', newStoryboard: 'Ny spellista', allStoryboards: 'Alla spellistor',
    sbMeta: (size, theme, n) => `${size} · ${theme} · ${n === 1 ? '1 tavla' : n + ' tavlor'}`, nowPlays: names => `Nu: ${names}`, playingHere: 'Spelas på den här skärmen', clockOnly: 'klockan',
    viewWeek: 'Vecka', viewBoards: 'Tavlor', viewDisplay: 'Visning',
    anyTime: 'När som helst', anyTimeNone: 'Alla tavlor har en tid.', anyTimeHint: 'Ingen tid satt, så den turas om med de andra när den kan.', aloneTag: 'Ensam',
    seeInWeek: 'Se den i veckan', whenShows: 'När den visas',
    copyToTitle: 'Lägg till i en spellista', copyToNote: 'Spellistan visar samma tavla, så en ändring syns i båda. Duplicera den först för en egen.', copiedTo: name => `Kopierad till ${name}.`, cancel: 'Avbryt',
    displayNote: 'De här beskriver skärmen.',
    exIntro: 'Visa en mall på den här skärmen, eller lägg till en av dess tavlor i en spellista du har. Båda sätten ger en kopia bland dina tavlor.', importTitle: 'Från en fil', fromOthers: 'Från andra', laterShort: 'Senare',
    useAsNew: 'Använd som ny spellista', addToSb: 'Lägg till i en spellista',
    yourData: 'Dina uppgifter', dataCounts: (n, max) => `${n} av ${max} spellistor`, connections: 'Kopplingar', submissions: 'Dina bidrag',
    todaysPlaylist: 'Dagens spellista', playlistFor: day => `Spellista för ${day}`, playlistNote: 'Räknas ut från när varje tavla visas. Ändra veckan för att ändra den.',
    nowShowing: (names, until, next) => until ? `Nu visas ${names} till ${until}, sedan ${next}` : `Nu visas ${names}`,
    prevWeek: 'Förra veckan', nextWeek: 'Nästa vecka', weekOf: (a, b) => `${a} till ${b}`, fromYesterday: 'från igår', comingDates: 'Kommande datum', allDay: 'hela dagen',
    weekEmpty: 'Ingen tavla har en tid än, så alla turas om hela dagen. Dra nedåt i en dag för att ge en av dem en tid.',
    addATime: 'Lägg till en tid', timeCardTitle: 'Vilken tavla visas då?', newBoardShort: 'Ny tavla', maxTimes: 'Den tavlan har redan åtta tider, så många den kan ha.',
    edit: 'Redigera', fullscreen: 'Helskärm', exitFs: 'Lämna helskärm', sound: 'Ljud', on: 'På', off: 'Av', share: 'Dela', done: 'Klar',
    pages: 'Tavlor', board: 'Tavla', boards: 'Tavlor', cue: 'Det här är en demo. Tryck på Redigera för att göra den till din.', gotIt: 'Uppfattat',
    shareTitle: 'Visa det här på en annan skärm', shareBody: 'Länken bär spellistan som den är nu. Om du ändrar den senare, dela den igen.', linkCopied: 'Länken är kopierad. Öppna den på den andra skärmen.', qrLarge: 'Visa QR-koden i full storlek', close: 'Stäng', copy: 'Kopiera länk', copied: 'Kopierad',
    shareLong: 'Spellistan är för stor för en QR-kod (Quick Response). Länken fungerar ändå.',
    newBoard: 'Ny tavla', addPage: 'Lägg till en tavla', layout: 'Layout', channel: 'Kanal',
    size: 'Rutnät', custom: 'Egen', fill: 'Fyll skärmen', rows: 'Rader', cols: 'Kolumner', theme: 'Tema', transition: 'Övergång', speed: 'Hastighet',
    quiet: 'Tysta timmar', quietBlank: 'Tom', quietDim: 'Dämpad', to: 'till', saved: 'Sparas automatiskt i den här webbläsaren.',
    duplicate: 'Duplicera', exportJ: 'Exportera JSON', importJ: 'Importera JSON', del: 'Ta bort', name: 'Namn',
    offline: n => `Livedata ${n} min gammal`,
    clear: 'Rensa', center: 'Centrera rader', flaps: 'flappar använda', full: 'Zonen är full. Ta bort något för att få plats.',
    blankNote: ch => `“${ch}” finns inte på flapparna och visas som tomt.`,
    station: 'Station', city: 'Stad', label: 'Etikett', date: 'Datum', format: 'Format', text: 'Löptext',
    quoteNote: 'Byter bland några ordspråk varje minut.', editing: 'Redigerar',
    stageRole: 'split-flap-tavla', stageLabel: (board, n, of, name) => n ? `${board}, tavla ${n} av ${of}${name ? ', ' + name : ''}` : board,
    page: 'Tavla', recommended: 'Rekommenderad', tplSizeOwn: 'Storleken mallen är gjord för. Välj en annan så visar förhandsvisningen den.', tplSizeOther: s => `Visas i storleken du valde. Mallen är gjord för ${s}.`,
    unsetHint: { weather: 'Välj en stad nedan. Till dess visar tavlan VÄDER och ett streck.', rotating: 'Lägg till ett meddelande nedan. Till dess visar tavlan MEDDELANDEN och ett streck.', url: 'Lägg till en webbadress nedan. Till dess visar tavlan FRÅN WEBBEN och ett streck.', departuresNear: 'Den här visar hållplatsen närmast skärmen när den har en plats. Välj en under Visning, eller välj en hållplats nedan. Till dess säger tavlan LADDAR.',
      sl: 'Välj en station nedan. Till dess visar tavlan SL och ett streck.', headlines: 'Lägg till ett flöde nedan. Till dess visar tavlan RUBRIKER och ett streck.', worldtime: 'Lägg till en stad nedan. Till dess visar tavlan VÄRLDSKLOCKA och ett streck.',
      departures: 'Välj en hållplats nedan. Till dess visar tavlan AVGÅNGAR och ett streck.', markets: 'Välj en symbol nedan. Till dess visar tavlan ett streck.', rates: 'Välj en bank nedan. Till dess visar tavlan RÄNTOR och ett streck.' },
    compHint: 'Tryck på en flapp och skriv. Den här raden finns bara i redigeraren.', copySuffix: ' kopia', searching: 'Söker', noMatch: 'Ingen träff',
    modes: 'Visa', eta: 'Tider', etaMin: 'Minuter', etaClock: 'Klockslag', etaCycle: 'Växla', allDays: 'Alla dagar',
    modeNames: { METRO: 'Tunnelbana', TRAIN: 'Pendeltåg', TRAM: 'Spårvagn', BUS: 'Buss', SHIP: 'Båt' },
    dayShort: ['Sön', 'Mån', 'Tis', 'Ons', 'Tor', 'Fre', 'Lör'],
    speeds: { fast: 'Snabb', gentle: 'Lugn', authentic: 'Äkta' },
    transitions: { classic: 'Klassisk', wave: 'Våg', drift: 'Drift', curtain: 'Ridå' },
    layouts: { full: 'Hel', header: 'Rubrik och text', split: 'Delad', ticker: 'Löprad', stacked: 'Staplad' },
    zoneNames: { full: ['Hela tavlan'], header: ['Rubrikrad', 'Text'], split: ['Vänster', 'Höger'], ticker: ['Text', 'Löprad'], stacked: ['Övre halvan', 'Nedre halvan'] },
    channels: { message: 'Meddelande', clock: 'Klocka och datum', bigclock: 'Stor klocka', bigtext: 'Stor text', countdown: 'Nedräkning', sl: 'SL-avgångar', weather: 'Väder', art: 'Färgmönster', quote: 'Citat',
      rotating: 'Växlande meddelanden', menu: 'Meny', wordclock: 'Ordklocka', today: 'Idag', electricity: 'Elpris', currency: 'Valuta', onthisday: 'Den här dagen', url: 'Följ en URL', letterclock: 'Bokstavsklocka' },
    colour: 'Färg', rainbow: 'Regnbåge', themeColour: 'Tema', pattern: 'Mönster', every: 'Byt var', seconds: 's',
    patterns: { rainbow: 'Regnbåge', nordic: 'Nordiska flaggor', rain: 'Regn', confetti: 'Konfetti', wave: 'Våg', checker: 'Rutor' },
    view: 'Visa', views: { now: 'Nu', hours: 'Kommande timmar', days: 'Tre dagar' },
    versionLog: 'Versionslogg', back: 'Tillbaka', logNote: 'Varje version är en release, den senaste först. Samma logg finns på', bigTextLabel: 'Text', bigTextNote: 'Stora bokstäver är 5 blad höga, så en 6 x 22-skärm rymmer ungefär 5 tecken åt gången; längre text bläddras ord för ord.',
    slHome: 'Följ min hemstation på SL-kartan', slHomeNone: 'Stjärnmärk en station på SL-kartan för att använda den här.', slHomeIs: name => `Hemstation: ${name}`,
    slMapLink: 'Öppna SL-kartan', slWhat: 'Alla hållplatser i Storstockholms Lokaltrafik (SL): tunnelbana, pendeltåg, spårvagn, buss och båt.',
    volume: 'Volym', soundStyle: 'Bladljud', sounds: { clack: 'Klack', heavy: 'Tungt', soft: 'Mjukt', tick: 'Tick' }, preview: 'Förhandsvisa', previewSound: 'Spela prov',
    templates: 'Börja från en mall', useTemplate: 'Skapa', kioskLink: 'Länk för en väggskärm (kioskläge, inga kontroller)',
    previewing: name => name,
    imported: 'Spellistan öppnades från en länk.', importedCopy: 'Spellistan öppnades från en länk. Tavlor du redan hade med annat innehåll behölls, och länkens kom in som kopior.', importFail: 'Filen är inte en spellista.', linkFail: 'Länken till spellistan är trasig eller ofullständig.',
    jsonNote: 'JSON betyder JavaScript Object Notation: en textkopia av en spellista som du kan spara eller flytta till en annan webbläsare.',
    chip: name => `Infoga ${name} färgbricka`, typeOnBoard: 'Skriv på tavlan', duration: 'Tid i sekunder',
    moveUp: 'Flytta upp', moveDown: 'Flytta ned', lang: 'Språk', langHint: 'För redigeraren och för det tavlorna skriver, som dagar och månader. Sparas i den här webbläsaren.', controls: 'Kontroller', editor: 'Redigerare',
    boardLink: 'Länk till spellistan',
    addTime: 'Lägg till en tid till', removeTime: 'Ta bort den här tiden', rolls: 'Rullningar', rollStart: 'Rulla alla blad när skärmen startar', rollHourly: 'Rulla igen varje hel timme', pageTransition: 'Övergång till den här tavlan', boardDefault: name => `Spellistans (${name.toLowerCase()})`, showAlone: 'Visa ensam medan den är på', showAloneHint: 'Tavlor utan tid väntar tills den är slut.', winDays: 'Veckodagar', winDate: 'Ett datum', everyYear: 'Varje år',
    monthShort: ['jan', 'feb', 'mars', 'apr', 'maj', 'juni', 'juli', 'aug', 'sep', 'okt', 'nov', 'dec'],
    accSignedOut: 'Utloggad. Logga in för att synka', signInToSync: 'Logga in för att synka',
    accSignedOutBody: n => (n ? `Du loggades ut, så ${n === 1 ? 'en ändring här har' : n + ' spellistor här har ändringar som'} inte nått ditt konto än. ` : 'Du loggades ut. ') + 'Dina spellistor finns kvar här. Logga in igen för att synka dem.',
    confirmSignOutUnsynced: n => `${n === 1 ? '1 spellista har ändringar' : n + ' spellistor har ändringar'} som inte nått ditt konto än. Anslut och försök igen, eller logga ut ändå och behåll ${n === 1 ? 'den' : 'dem'} här som gäst.`,
    signOutAnyway: 'Logga ut ändå', signOutAgain: 'Tryck igen för att logga ut', deleteAgain: 'Tryck igen för att radera',
    keptAsGuest: n => `Utloggad. ${n === 1 ? '1 spellista med osynkade ändringar finns' : n + ' spellistor med osynkade ändringar finns'} kvar här som gäst.`,
    refusedBoard: (name, why) => `”${name}” finns bara här: ${why === 'too_many_boards' ? 'ditt konto har 50 spellistor, så många det rymmer.' : why === 'too_big' ? 'den är för stor att spara.' : 'kontot kunde inte ta emot den.'}`,
    signIn: 'Logga in', renameBoard: 'Byt namn på spellistan',
    account: 'Konto', accGuestSub: 'Gäst, spellistor bara i den här webbläsaren', changedAt: at => `Ändrad ${at}`, accSynced: 'Synkad', accSyncedExcept: n => `Synkad, utom ${n === 1 ? '1 spellista' : n + ' spellistor'}`, accWaiting: 'Väntar på att synka', accFailed: 'Kunde inte synka, försöker igen',
    accGuestBody: 'Du använder Split-Flap som gäst. Dina spellistor sparas bara i den här webbläsaren, så om du rensar den eller byter telefon eller dator försvinner de.',
    accSignInBody: 'Logga in med Google så sparas dina spellistor med ditt konto, på alla enheter där du loggar in.', signInGoogle: 'Logga in med Google', accPrivacy: 'Vad ett konto sparar',
    offerTitle: n => n === 1 ? 'Det finns 1 spellista i den här webbläsaren från innan du loggade in.' : `Det finns ${n} spellistor i den här webbläsaren från innan du loggade in.`,
    offerBody: n => n === 1 ? 'Spara den med ditt konto, eller låt den ligga kvar här som den är.' : 'Bocka ur de du vill låta ligga kvar här som de är. Resten går till ditt konto.', offerKeep: 'Spara med mitt konto', offerLeave: n => n === 1 ? 'Låt ligga kvar' : 'Låt alla ligga kvar',
    offerDone: (n, m = 0) => { const a = n === 1 ? '1 spellista' : `${n} spellistor`, b = m === 1 ? '1 tavla' : `${m} tavlor`; return `${n && m ? `${a} och ${b}` : n ? a : b} finns nu i ditt konto.`; },
    signInPrompt: safari => 'Dina spellistor finns bara i den här webbläsaren. Logga in så är de säkra och finns på dina andra enheter.' + (safari ? ' Safari rensar dessutom en webbplats lagring efter 7 dagar utan besök.' : ''), notNow: 'Inte nu',
    exportAll: 'Exportera mitt konto', signOut: 'Logga ut', confirmSignOut: 'Dina spellistor tas bort från den här webbläsaren och finns kvar i ditt konto.',
    deleteAccount: 'Radera kontot', confirmDelete: 'Det raderar ditt konto och alla spellistor i det, och det går inte att ångra.', otherDevice: ' (kopia)',
    signInFailed: 'Inloggningen startade inte. Försök igen om en stund.', accountDeleted: 'Ditt konto och dess spellistor är raderade.', signInAgainToDelete: 'Logga in igen av säkerhetsskäl och radera sedan kontot.',
    deleteFailed: 'Kontot kunde inte raderas. Försök igen om en stund.', startGuest: 'Som gäst sparas dina spellistor bara i den här webbläsaren.', syncFailedMark: 'Kunde inte synka',
    help: 'Hjälp', helpSub: 'Så fungerar Split-Flap', gridIs: (r, c) => `Skärmen är ${r} × ${c} flappar.`, changeSize: 'Ändra storleken',
    chooseContent: 'Välj innehåll',
    startTitle: 'Börja från en mall', skip: 'Behåll demospellistan',
    moveNamed: name => `Flytta ${name}`, reorderHint: 'Dra för att ändra ordning, eller markera handtaget och använd piltangenterna',
    boardsCount: n => n === 1 ? '1 tavla' : `${n} tavlor`, templatesCount: n => `${n} mallar`, pagesCount: n => n === 1 ? '1 tavla' : `${n} tavlor`,
    pageName: 'Tavlans namn', zones: 'Zoner', tapZone: 'Tryck på en zon för att välja vad den visar.', tapZoneOne: 'Tryck på zonen för att välja vad den visar.',
    showFor: 'Visa i', daysLabel: 'Dagar', from: 'Från', saveImage: 'Spara som bild', less: 'Mindre', more1: 'Mer',
    change: 'Byt', moreOptions: 'Fler alternativ', fewer: 'Färre alternativ', searchContent: 'Sök innehåll',
    shapeNote: (h, w) => `Förhandsvisningarna ritas i zonens form: ${h} × ${w} flappar.`, later: 'Kommer med reläet', noResults: 'Inget matchar. Prova ett kortare ord.',
    remove: 'Ta bort', changeCity: 'Sök efter en annan stad', searchCity: 'Sök efter en stad', addStation: 'Lägg till station', maxStations: 'Högst sex stationer.',
    seeAll: n => `Visa alla ${n}`,
    whereTitle: 'Var finns den här skärmen?', whereHint: 'Demon och alla mallar byggs för platsen: vädret, närmaste hållplats, helgdagar, valutan och klockan.', notHereYet: 'Inte tillgängligt här än',
    feedAdd: 'Lägg till ett flöde med dess adress', feedBad: 'Det är inte en flödesadress som går att läsa: den behöver börja med https:// på en öppen webbplats.',
    feedSignedIn: 'Ett annat flöde sparas med ditt konto under Konto, och väggskärmar kan sedan läsa det.', feedGuest: 'Som gäst fungerar ett annat flöde bara om det låter andra webbplatser läsa det. Logga in så fungerar alla flöden, på väggskärmar också.',
    connDefault: { av: 'Alpha Vantage', sheet: 'Mitt kalkylark', feed: 'Flöde', json: 'Flöde' }, connKinds: { av: 'API-nyckel', sheet: 'Kalkylark', feed: 'Flöde', json: 'JSON' },
    connNone: 'Dina egna källor, till exempel en Alpha Vantage-nyckel eller ett publicerat kalkylark, visas här när du lagt till en i en ruta.',
    connLocal: 'Sparas i den här webbläsaren. Logga in för att spara dem med ditt konto också.', connSynced: 'Sparas med ditt konto, och i den här webbläsaren tills du loggar ut.', connLocalOnly: 'Sparas bara i den här webbläsaren just nu.',
    connBad: 'Det ser inte ut som en nyckel eller en https-länk.',
    searchSymbol: 'Sök efter en aktie eller fond', maxSymbols: 'Högst åtta, som turas om.', viaLondon: 'Svensk, prissatt via London', typeSymbol: 'Skriv en symbol och tryck Enter',
    ownSymbolHint: 'Som din källa skriver den: IBM eller ERIC-B.STO för en nyckel, kolumnen Symbol för ett kalkylark.',
    yourKey: 'Din Alpha Vantage-nyckel', yourSheet: 'Ditt publicerade kalkylark (CSV-länk)',
    keyHint: 'Aldrig i tavlan eller dess länk. Sparas i den här webbläsaren, och med ditt konto när du är inloggad. Alla vid den här skärmen kan läsa den, så använd en gratisnyckel gjord för detta. En gratisnyckel tillåter 25 anrop om dagen: tavlan frågar en gång per symbol efter varje stängning.',
    sheetHint: 'Sparas i den här webbläsaren, och med ditt konto när du är inloggad. Med ett historikblock per symbol börjar linjen från första dagen; utan det bygger skärmen den av priserna allteftersom dagarna går.', getKey: 'Skaffa en gratisnyckel', sheetHow: 'Så ställer du in kalkylarket',
    addStop: 'Sök efter en hållplats eller station', maxStops: 'Högst fyra hållplatser.', nearby: 'Nära platsen under Visning',
    nearIs: (stop, city) => `Närmaste hållplats till ${city}: ${stop}. Välj en annan nedan för att byta.`, nearLooking: 'Letar efter närmaste hållplats…',
    nearNeedsPlace: 'Välj en plats under Visning så väljs närmaste hållplats åt dig, eller sök efter en nedan.',
    lineTemplate: 'Radmall', insert: 'Infoga', firstItem: 'Första posten i flödet', sampleFeed: 'Ett exempelflöde, tills du lägger till en adress', prints: 'Tavlan skriver',
    feedErr: 'Adressen gick inte att läsa. Den kanske inte låter andra webbplatser läsa den.', loadingFeed: 'Hämtar flödet.',
    unknownToken: k => `”${k}” finns inte i flödet och skrivs inte ut.`,
    sunFrom: city => `Soltider för ${city}, platsen under Visning.`, sunNeedsLoc: 'Soltider behöver en plats. Välj en under', boardName: 'Spellistans namn',
    boardLoc: 'Plats', locHint: 'Var den här skärmen finns. Nya tavlor utgår från den: vädret, närmaste hållplats, helgdagar, valutan och 12 eller 24 timmar.',
    locAgain: 'Välj staden igen för att lägga till dess land och tidszon, så att helgdagar och valuta följer med.',
    tzNote: (city, tz, here) => `${city} ligger i ${tz} och skärmens klocka i ${here}. Tiderna i veckan följer skärmens klocka. Avgångar visar hållplatsens egen tid.`,
    current: 'Nuvarande', open: 'Öppna', exportB: 'Exportera', importB: 'Importera en spellista',
    undo: 'Ångra', redo: 'Gör om', composerMode: 'Redigeringsläge', type: 'Skriv', paint: 'Måla', photo: 'Foto',
    brush: 'Pensel', fillTool: 'Fyll', mirror: 'Spegla', paintColour: 'Målarfärg', blankChip: 'Tom',
    choosePhoto: 'Välj foto', takePhoto: 'Ta foto', sampleImage: 'Inget foto valt', sampleNote: 'Välj ett foto eller ta ett. Reglagen placerar det sedan i zonen.',
    photoFail: 'Filen gick inte att öppna som bild.', photoLocal: 'Fotot stannar i den här webbläsaren. Bara flapparna sparas.',
    zoom: 'Zoom', posX: 'Vågrät position', posY: 'Lodrät position', dither: 'Rastrering', ditherHint: 'Blandar flappar för att antyda mellanfärgerna', blankColour: 'Räkna tomma flappar som en färg',
    today: 'Idag', yesterday: 'Igår', drafts: 'Tidigare meddelanden', draftsNote: 'Sparas i den här webbläsaren. Ett meddelande sparas här när du lämnar redigeraren efter en ändring.', noDrafts: 'Inget ännu. Ett meddelande sparas här när du lämnar redigeraren efter en ändring.', use: 'Använd',
  }
};
