// Interface copy, English and Swedish. Board content (day names, NOW/NU) lives in
// content.js because it is drawn on flaps, not in the page.

export const STR = {
  en: {
    // 0.7.1: My boards.
    secMyBoards: 'My boards', templatesShort: 'Templates', signInNotFinished: 'Sign-in did not finish, so nothing changed. Try again, and finish it in this same browser.', myFull: 'My boards holds 100 boards, the most it can.', savedToMy: name => `${name} is saved to My boards.`,
    bpSize: (r, c) => `Kept at ${r} × ${c}, the size it was made at. A copy fits the storyboard it goes into.`, onScreen: 'On screen', bpNoTimes: 'Times are set on the copy in a storyboard, since they belong to its plan.',
    searchMy: 'Search My boards', myEmptyTitle: 'Your boards to start from', myEmptyBody: 'Save a board here from any storyboard or template, and add a copy of it to any storyboard later. Nothing goes here unless you save it.',
    browseExplore: 'Browse Explore', importShort: 'Import', allSizes: 'All sizes', showAllSizes: n => `Show all sizes (${n})`, noneThisSize: 'None at this size yet.',
    previewOnBoard: (r, c) => `Shown on the big board at this storyboard's size, ${r} × ${c}.`, cutWarn: n => `${n === 1 ? '1 typed or painted flap falls' : n + ' typed or painted flaps fall'} outside at this size and will be cut.`,
    addHere: 'Add to this storyboard', addedTo: (name, sb) => `${name} is added to ${sb}.`,
    fromFile: 'A file', fromVestaboard: 'A Vestaboard message', importFileNote: 'A board file goes to My boards, and a storyboard file becomes a storyboard.', chooseFile: 'Choose a file',
    vbNote: (r, c) => `Paste the message, one line per row. It is centred, in capitals, at ${r} × ${c}, and shown on the big board as you type.`,
    offerTitle2: (n, m) => { const a = n === 1 ? '1 storyboard' : `${n} storyboards`, b = m === 1 ? '1 board in My boards' : `${m} boards in My boards`; return `There ${n + m === 1 ? 'is' : 'are'} ${n && m ? `${a} and ${b}` : n ? a : b} in this browser from before you signed in.`; },
    offerKeepN: n => `Keep with my account (${n})`, vbTooMany: n => `${n === 1 ? 'The last line does' : `The last ${n} lines do`} not fit and will be left out.`,
    // 0.7: the sections, the storyboard and the week. Words from GLOSSARY.md.
    secStoryboards: 'Storyboards', secExplore: 'Explore', secAccount: 'Account', secSettings: 'Settings', searchLater: 'Search, coming later',
    more: 'More', mOpen: 'Open', mRename: 'Rename', mDuplicate: 'Duplicate', mSave: 'Save to my boards', mCopyTo: 'Copy to', mShare: 'Share', mShareImage: 'Share as image', mExport: 'Export', mDelete: 'Delete', mDeleteAgain: 'Press again to delete',
    changedTitle: 'Some words have moved', changedBody: 'Nothing you made has changed, only what things are called.',
    changedRows: [['What was a board', 'is now a storyboard'], ['What was a page', 'is now a board'], ['The playlist', "is now worked out for you, as Today's playlist"]],
    sbIntro: 'A storyboard is what a screen plays: its boards in order, and when each one shows.', newStoryboard: 'New storyboard', allStoryboards: 'All storyboards',
    sbMeta: (size, theme, n) => `${size} · ${theme} · ${n === 1 ? '1 board' : n + ' boards'}`, nowPlays: names => `Now: ${names}`, playingHere: 'Playing on this screen', clockOnly: 'the clock',
    viewWeek: 'Week', viewBoards: 'Boards', viewDisplay: 'Display',
    anyTime: 'Any time', anyTimeNone: 'Every board has a time.', anyTimeHint: 'No time set, so it takes turns with the others whenever it can.', aloneTag: 'Alone',
    seeInWeek: 'See it in the week', whenShows: 'When it shows',
    copyToTitle: 'Copy to a storyboard', copyToNote: 'The copy keeps what the board shows, and leaves its times behind.', copiedTo: name => `Copied to ${name}.`, cancel: 'Cancel',
    displayNote: 'These describe the display. When screens arrive, a screen can have its own size, theme and quiet hours.',
    exIntro: 'Use a template as a new storyboard, or copy one of its boards into a storyboard you have.', importTitle: 'From a file', fromOthers: 'From other people', laterShort: 'Later',
    useAsNew: 'Use as a new storyboard', addToSb: 'Add to a storyboard',
    yourData: 'Your data', dataCounts: (n, max) => `${n} of ${max} storyboards`, connections: 'Connections', submissions: 'Your submissions',
    todaysPlaylist: "Today's playlist", playlistFor: day => `Playlist for ${day}`, playlistNote: 'Worked out from when each board shows. Change the week to change it.',
    nowShowing: (names, until, next) => until ? `Now showing ${names} until ${until}, then ${next}` : `Now showing ${names}`,
    prevWeek: 'Previous week', nextWeek: 'Next week', weekOf: (a, b) => `${a} to ${b}`, fromYesterday: 'from yesterday', comingDates: 'Coming dates', allDay: 'all day',
    weekEmpty: 'No board has a time yet, so they all take turns all day. Drag down a day to give one a time.',
    addATime: 'Add a time', timeCardTitle: 'Which board shows then?', newBoardShort: 'New board', maxTimes: 'That board has eight times already, the most it can have.',
    edit: 'Edit', fullscreen: 'Fullscreen', exitFs: 'Exit fullscreen', sound: 'Sound', on: 'On', off: 'Off', share: 'Share', done: 'Done',
    pages: 'Boards', board: 'Board', boards: 'Boards', cue: 'This board is yours. Press Edit to make it say anything.', gotIt: 'Got it',
    shareTitle: 'Open this storyboard on another screen', shareBody: 'The link carries the whole storyboard.', copy: 'Copy link', copied: 'Copied',
    shareLong: 'This storyboard is too big for a QR (Quick Response) code. The link still works.',
    newBoard: 'New board', addPage: 'Add a board', layout: 'Layout', channel: 'Channel',
    size: 'Grid size', custom: 'Custom', fill: 'Fill screen', rows: 'Rows', cols: 'Columns', theme: 'Theme', transition: 'Transition', speed: 'Speed',
    quiet: 'Quiet hours', quietBlank: 'Blank', quietDim: 'Dim', to: 'to', saved: 'Saved automatically in this browser.',
    duplicate: 'Duplicate', exportJ: 'Export JSON', importJ: 'Import JSON', del: 'Delete', name: 'Name',
    offline: n => `Live data ${n} min old`,
    clear: 'Clear', center: 'Centre rows', flaps: 'flaps used', full: 'The zone is full. Delete something to make room.',
    blankNote: ch => `“${ch}” is not on the flaps, so it shows as blank.`,
    station: 'Station', city: 'City', label: 'Label', date: 'Date', format: 'Format', text: 'Ticker text',
    quoteNote: 'Rotates through a short set of proverbs every minute.', editing: 'Editing',
    stageRole: 'split-flap board', stageLabel: (board, n, of, name) => n ? `${board}, board ${n} of ${of}${name ? ', ' + name : ''}` : board,
    page: 'Board', typeHere: 'TYPE HERE', copySuffix: ' copy', searching: 'Searching', noMatch: 'No match',
    modes: 'Show', eta: 'Times', etaMin: 'Minutes', etaClock: 'Clock', etaCycle: 'Alternate', allDays: 'Every day',
    modeNames: { METRO: 'Metro', TRAIN: 'Train', TRAM: 'Tram', BUS: 'Bus', SHIP: 'Boat' },
    dayShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    speeds: { fast: 'Fast', gentle: 'Gentle', authentic: 'Authentic' },
    transitions: { classic: 'Classic', wave: 'Wave', drift: 'Drift', curtain: 'Curtain' },
    layouts: { full: 'Full', header: 'Header and body', split: 'Split', ticker: 'Ticker row', stacked: 'Stacked' },
    zoneNames: { full: ['Whole board'], header: ['Header row', 'Body'], split: ['Left', 'Right'], ticker: ['Body', 'Ticker row'], stacked: ['Top half', 'Bottom half'] },
    channels: { message: 'Message', clock: 'Clock and date', bigclock: 'Big clock', bigtext: 'Big text', countdown: 'Countdown', sl: 'SL departures', weather: 'Weather', art: 'Colour pattern', quote: 'Quotes',
      rotating: 'Rotating messages', menu: 'Menu', wordclock: 'Word clock', today: 'Today', electricity: 'Electricity price', currency: 'Currency', onthisday: 'On this day', url: 'Follow a URL', letterclock: 'Letter clock' },
    colour: 'Colour', rainbow: 'Rainbow', themeColour: 'Theme', pattern: 'Pattern', every: 'Change every', seconds: 's',
    patterns: { rainbow: 'Rainbow', nordic: 'Nordic flags', rain: 'Rain', confetti: 'Confetti', wave: 'Wave', checker: 'Checker' },
    view: 'Show', views: { now: 'Now', hours: 'Next hours', days: 'Three days' },
    versionLog: 'Version log', back: 'Back', logNote: 'Each version is a release, newest first. The same log is on', bigTextLabel: 'Text', bigTextNote: 'Big letters are 5 flaps tall, so a 6 x 22 board fits about 5 characters at a time; longer text moves through word by word.',
    slHome: 'Follow my home station on the SL map', slHomeNone: 'Star a station on the SL map to use it here.', slHomeIs: name => `Home station: ${name}`,
    slMapLink: 'Open the SL map', slWhat: 'Any Storstockholms Lokaltrafik (SL) stop: metro, commuter train, tram, bus and boat.',
    volume: 'Volume', soundStyle: 'Flap sound', sounds: { clack: 'Clack', heavy: 'Heavy', soft: 'Soft', tick: 'Tick' }, preview: 'Preview', previewSound: 'Play sample',
    templates: 'Start from a template', useTemplate: 'Create', kioskLink: 'Link for a wall screen (kiosk mode, no controls)',
    previewing: name => name,
    imported: 'Storyboard opened from a link.', importFail: 'That file is not a storyboard.', linkFail: 'That storyboard link is damaged or incomplete.',
    jsonNote: 'JSON means JavaScript Object Notation: a plain text copy of a storyboard you can keep or move to another browser.',
    chip: name => `Insert ${name} chip`, typeOnBoard: 'Type on the board', duration: 'Duration in seconds',
    moveUp: 'Move up', moveDown: 'Move down', lang: 'Language', langHint: 'For the editor and for what boards print, like days and months. Kept in this browser.', controls: 'Controls', editor: 'Editor',
    boardLink: 'Storyboard link',
    // editor drawer (DESIGN-HANDOVER-editor.md)
    addTime: 'Add another time', removeTime: 'Remove this time', rolls: 'Rolls', rollStart: 'Roll every flap when the display starts', rollHourly: 'Roll again on the hour', pageTransition: 'Transition to this board', boardDefault: name => `Storyboard default (${name})`, showAlone: 'Show alone while this is on', showAloneHint: 'Boards without a time wait until it ends.', winDays: 'Days of the week', winDate: 'A date', everyYear: 'Every year',
    monthShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    accSignedOut: 'Signed out. Sign in to sync', signInToSync: 'Sign in to sync',
    accSignedOutBody: n => (n ? `You were signed out, so ${n === 1 ? 'a change here has' : n + ' storyboards here have changes that have'} not reached your account yet. ` : 'You were signed out. ') + 'Your storyboards are still here. Sign in again to sync them.',
    confirmSignOutUnsynced: n => `${n === 1 ? '1 storyboard has changes' : n + ' storyboards have changes'} that have not reached your account yet. Connect and try again, or sign out anyway and keep ${n === 1 ? 'it' : 'them'} here as a guest.`,
    signOutAnyway: 'Sign out anyway', signOutAgain: 'Press again to sign out', deleteAgain: 'Press again to delete',
    keptAsGuest: n => `Signed out. ${n === 1 ? '1 storyboard with unsynced changes is' : n + ' storyboards with unsynced changes are'} kept here as a guest.`,
    refusedBoard: (name, why) => `“${name}” is kept here only: ${why === 'too_many_boards' ? 'your account holds 50 storyboards, the most it can.' : why === 'too_big' ? 'it is too big to store.' : 'the account could not take it.'}`,
    signIn: 'Sign in', renameBoard: 'Rename storyboard',
    account: 'Account', accGuestSub: 'Guest, storyboards in this browser only', changedAt: at => `Changed ${at}`, accSynced: 'Synced', accSyncedExcept: n => `Synced, except ${n === 1 ? '1 storyboard' : n + ' storyboards'}`, accWaiting: 'Waiting to sync', accFailed: 'Could not sync, it will try again',
    accGuestBody: 'You are using Split-Flap as a guest. Your storyboards are kept in this browser only, so clearing its data or changing phone or computer loses them.',
    accSignInBody: 'Sign in with Google and your storyboards are kept with your account, on any device you sign in on.', signInGoogle: 'Sign in with Google', accPrivacy: 'What an account stores',
    offerTitle: n => n === 1 ? 'There is 1 storyboard in this browser from before you signed in.' : `There are ${n} storyboards in this browser from before you signed in.`,
    offerBody: n => n === 1 ? 'Keep it with your account, or leave it here as it is.' : 'Untick any you want to leave here as they are. The rest go to your account.', offerKeep: 'Keep with my account', offerLeave: n => n === 1 ? 'Leave here' : 'Leave them all here',
    offerDone: (n, m = 0) => { const a = n === 1 ? '1 storyboard' : `${n} storyboards`, b = m === 1 ? '1 board from My boards' : `${m} boards from My boards`, both = n && m ? `${a} and ${b}` : n ? a : b; return `${both} ${n + m === 1 ? 'is' : 'are'} now in your account.`; },
    signInPrompt: safari => 'Your storyboards live only in this browser. Sign in to keep them safe and on your other devices.' + (safari ? " Safari also clears a site's storage after 7 days without a visit." : ''), notNow: 'Not now',
    exportAll: 'Export my account', signOut: 'Sign out', confirmSignOut: 'Your storyboards leave this browser and stay in your account.',
    deleteAccount: 'Delete account', confirmDelete: 'This deletes your account and every storyboard in it, and it cannot be undone.', otherDevice: ' (copy)',
    signInFailed: 'Sign in did not start. Try again in a moment.', accountDeleted: 'Your account and its storyboards are deleted.', signInAgainToDelete: 'For safety, sign in again, then delete the account.',
    deleteFailed: 'The account could not be deleted. Try again in a moment.', startGuest: 'As a guest, your storyboards are kept in this browser only.', syncFailedMark: 'Could not sync',
    help: 'Help', helpSub: 'How Split-Flap works', gridIs: (r, c) => `The display is ${r} × ${c} flaps.`, changeSize: 'Change the size',
    chooseContent: 'Choose content',
    startTitle: 'Start from a template', skip: 'Keep the demo storyboard',
    moveNamed: name => `Move ${name}`, reorderHint: 'Drag to reorder, or focus the handle and use the arrow keys',
    boardsCount: n => n === 1 ? '1 board' : `${n} boards`, templatesCount: n => `${n} templates`, pagesCount: n => n === 1 ? '1 board' : `${n} boards`,
    pageName: 'Board name', zones: 'Zones', tapZone: 'Tap a zone to choose what it shows.', tapZoneOne: 'Tap the zone to choose what it shows.',
    showFor: 'Show for', daysLabel: 'Days', from: 'From', saveImage: 'Save as image', less: 'Less', more1: 'More',
    change: 'Change', moreOptions: 'More options', fewer: 'Fewer options', searchContent: 'Search content',
    shapeNote: (h, w) => `Previews are drawn at the shape of this zone: ${h} × ${w} flaps.`, later: 'Arrives with the relay', noResults: 'Nothing matches. Try a shorter word.',
    remove: 'Remove', changeCity: 'Search for another city', searchCity: 'Search for a city', addStation: 'Add a station', maxStations: 'Up to six stations.',
    lineTemplate: 'Line template', insert: 'Insert', firstItem: 'First item in the feed', sampleFeed: 'A sample feed, until you add an address', prints: 'The board will print',
    feedErr: 'This address could not be read. It may not allow other sites to read it.', loadingFeed: 'Fetching the feed.',
    unknownToken: k => `“${k}” is not in the feed, so it prints nothing.`,
    sunFrom: city => `Sun times for ${city}, the board location.`, sunNeedsLoc: 'Sun times need a location. Set one under', boardName: 'Storyboard name',
    boardLoc: 'Location', locHint: 'Used for sun times, and for weather zones that have no city of their own.',
    current: 'Current', open: 'Open', exportB: 'Export', importB: 'Import a storyboard',
    undo: 'Undo', redo: 'Redo', composerMode: 'Composer mode', type: 'Type', paint: 'Paint', photo: 'Photo',
    brush: 'Brush', fillTool: 'Fill', mirror: 'Mirror', paintColour: 'Paint colour', blankChip: 'Blank',
    choosePhoto: 'Choose photo', takePhoto: 'Take photo', sampleImage: 'No photo chosen', sampleNote: 'Choose a photo or take one. The sliders then place it in the zone.',
    photoFail: 'That file could not be opened as a picture.', photoLocal: 'The photo stays in this browser. Only the flaps are saved.',
    zoom: 'Zoom', posX: 'Horizontal position', posY: 'Vertical position', dither: 'Dithering', ditherHint: 'Mixes flaps to suggest the colours in between', blankColour: 'Count blank flaps as a colour',
    today: 'Today', yesterday: 'Yesterday', drafts: 'Earlier messages', draftsNote: 'Kept in this browser. A message is kept here when you leave the composer after changing it.', noDrafts: 'Nothing yet. A message is kept here when you leave the composer after changing it.', use: 'Use',
  },
  sv: {
    // 0.7.1: Mina tavlor.
    secMyBoards: 'Mina tavlor', templatesShort: 'Mallar', signInNotFinished: 'Inloggningen blev inte klar, så inget ändrades. Försök igen, och gör klart den i samma webbläsare.', myFull: 'Mina tavlor rymmer 100 tavlor, så många som går.', savedToMy: name => `${name} är sparad i Mina tavlor.`,
    bpSize: (r, c) => `Sparad i ${r} × ${c}, storleken den gjordes i. En kopia anpassas till storyboarden den läggs i.`, onScreen: 'På skärmen', bpNoTimes: 'Tider sätts på kopian i en storyboard, eftersom de hör till dess plan.',
    searchMy: 'Sök i Mina tavlor', myEmptyTitle: 'Dina tavlor att utgå från', myEmptyBody: 'Spara en tavla här från en storyboard eller mall, och lägg senare en kopia av den i vilken storyboard som helst. Inget hamnar här om du inte sparar det.',
    browseExplore: 'Titta i Utforska', importShort: 'Importera', allSizes: 'Alla storlekar', showAllSizes: n => `Visa alla storlekar (${n})`, noneThisSize: 'Inga i den här storleken än.',
    previewOnBoard: (r, c) => `Visas på den stora tavlan i storyboardens storlek, ${r} × ${c}.`, cutWarn: n => `${n === 1 ? '1 skriven eller målad flapp hamnar' : n + ' skrivna eller målade flappar hamnar'} utanför i den här storleken och klipps bort.`,
    addHere: 'Lägg till i den här storyboarden', addedTo: (name, sb) => `${name} är tillagd i ${sb}.`,
    fromFile: 'En fil', fromVestaboard: 'Ett Vestaboard-meddelande', importFileNote: 'En tavelfil hamnar i Mina tavlor, och en storyboardfil blir en storyboard.', chooseFile: 'Välj en fil',
    vbNote: (r, c) => `Klistra in meddelandet, en rad per rad. Det centreras, med versaler, i ${r} × ${c}, och visas på den stora tavlan medan du skriver.`,
    offerTitle2: (n, m) => { const a = n === 1 ? '1 storyboard' : `${n} storyboards`, b = m === 1 ? '1 tavla i Mina tavlor' : `${m} tavlor i Mina tavlor`; return `Det finns ${n && m ? `${a} och ${b}` : n ? a : b} i den här webbläsaren från innan du loggade in.`; },
    offerKeepN: n => `Spara med mitt konto (${n})`, vbTooMany: n => `${n === 1 ? 'Sista raden får' : `De sista ${n} raderna får`} inte plats och tas bort.`,
    // 0.7: sektionerna, storyboarden och veckan. Orden kommer från GLOSSARY.md.
    secStoryboards: 'Storyboards', secExplore: 'Utforska', secAccount: 'Konto', secSettings: 'Inställningar', searchLater: 'Sök, kommer senare',
    more: 'Mer', mOpen: 'Öppna', mRename: 'Byt namn', mDuplicate: 'Duplicera', mSave: 'Spara i mina tavlor', mCopyTo: 'Kopiera till', mShare: 'Dela', mShareImage: 'Dela som bild', mExport: 'Exportera', mDelete: 'Radera', mDeleteAgain: 'Tryck igen för att radera',
    changedTitle: 'Några ord har flyttat', changedBody: 'Inget du har gjort har ändrats, bara vad saker heter.',
    changedRows: [['Det som var en tavla', 'är nu en storyboard'], ['Det som var en sida', 'är nu en tavla'], ['Spellistan', 'räknas nu ut åt dig, som Dagens spellista']],
    sbIntro: 'En storyboard är det en skärm spelar: dess tavlor i ordning, och när var och en visas.', newStoryboard: 'Ny storyboard', allStoryboards: 'Alla storyboards',
    sbMeta: (size, theme, n) => `${size} · ${theme} · ${n === 1 ? '1 tavla' : n + ' tavlor'}`, nowPlays: names => `Nu: ${names}`, playingHere: 'Spelas på den här skärmen', clockOnly: 'klockan',
    viewWeek: 'Vecka', viewBoards: 'Tavlor', viewDisplay: 'Visning',
    anyTime: 'När som helst', anyTimeNone: 'Alla tavlor har en tid.', anyTimeHint: 'Ingen tid satt, så den turas om med de andra när den kan.', aloneTag: 'Ensam',
    seeInWeek: 'Se den i veckan', whenShows: 'När den visas',
    copyToTitle: 'Kopiera till en storyboard', copyToNote: 'Kopian behåller det tavlan visar, men inte dess tider.', copiedTo: name => `Kopierad till ${name}.`, cancel: 'Avbryt',
    displayNote: 'De här beskriver skärmen. När skärmar kommer kan en skärm få egen storlek, eget tema och egna tysta timmar.',
    exIntro: 'Använd en mall som ny storyboard, eller kopiera en av dess tavlor till en storyboard du har.', importTitle: 'Från en fil', fromOthers: 'Från andra', laterShort: 'Senare',
    useAsNew: 'Använd som ny storyboard', addToSb: 'Lägg till i en storyboard',
    yourData: 'Dina uppgifter', dataCounts: (n, max) => `${n} av ${max} storyboards`, connections: 'Kopplingar', submissions: 'Dina bidrag',
    todaysPlaylist: 'Dagens spellista', playlistFor: day => `Spellista för ${day}`, playlistNote: 'Räknas ut från när varje tavla visas. Ändra veckan för att ändra den.',
    nowShowing: (names, until, next) => until ? `Nu visas ${names} till ${until}, sedan ${next}` : `Nu visas ${names}`,
    prevWeek: 'Förra veckan', nextWeek: 'Nästa vecka', weekOf: (a, b) => `${a} till ${b}`, fromYesterday: 'från igår', comingDates: 'Kommande datum', allDay: 'hela dagen',
    weekEmpty: 'Ingen tavla har en tid än, så alla turas om hela dagen. Dra nedåt i en dag för att ge en av dem en tid.',
    addATime: 'Lägg till en tid', timeCardTitle: 'Vilken tavla visas då?', newBoardShort: 'Ny tavla', maxTimes: 'Den tavlan har redan åtta tider, så många den kan ha.',
    edit: 'Redigera', fullscreen: 'Helskärm', exitFs: 'Lämna helskärm', sound: 'Ljud', on: 'På', off: 'Av', share: 'Dela', done: 'Klar',
    pages: 'Tavlor', board: 'Tavla', boards: 'Tavlor', cue: 'Tavlan är din. Tryck Redigera och låt den säga vad du vill.', gotIt: 'Uppfattat',
    shareTitle: 'Öppna den här storyboarden på en annan skärm', shareBody: 'Länken bär hela storyboarden.', copy: 'Kopiera länk', copied: 'Kopierad',
    shareLong: 'Storyboarden är för stor för en QR-kod (Quick Response). Länken fungerar ändå.',
    newBoard: 'Ny tavla', addPage: 'Lägg till en tavla', layout: 'Layout', channel: 'Kanal',
    size: 'Rutnät', custom: 'Egen', fill: 'Fyll skärmen', rows: 'Rader', cols: 'Kolumner', theme: 'Tema', transition: 'Övergång', speed: 'Hastighet',
    quiet: 'Tysta timmar', quietBlank: 'Tom', quietDim: 'Dämpad', to: 'till', saved: 'Sparas automatiskt i den här webbläsaren.',
    duplicate: 'Duplicera', exportJ: 'Exportera JSON', importJ: 'Importera JSON', del: 'Ta bort', name: 'Namn',
    offline: n => `Livedata ${n} min gammal`,
    clear: 'Rensa', center: 'Centrera rader', flaps: 'flappar använda', full: 'Zonen är full. Ta bort något för att få plats.',
    blankNote: ch => `“${ch}” finns inte på flapparna och visas som tomt.`,
    station: 'Station', city: 'Stad', label: 'Etikett', date: 'Datum', format: 'Format', text: 'Löptext',
    quoteNote: 'Byter bland några ordspråk varje minut.', editing: 'Redigerar',
    stageRole: 'split-flap-tavla', stageLabel: (board, n, of, name) => n ? `${board}, tavla ${n} av ${of}${name ? ', ' + name : ''}` : board,
    page: 'Tavla', typeHere: 'SKRIV HÄR', copySuffix: ' kopia', searching: 'Söker', noMatch: 'Ingen träff',
    modes: 'Visa', eta: 'Tider', etaMin: 'Minuter', etaClock: 'Klockslag', etaCycle: 'Växla', allDays: 'Alla dagar',
    modeNames: { METRO: 'Tunnelbana', TRAIN: 'Pendeltåg', TRAM: 'Spårvagn', BUS: 'Buss', SHIP: 'Båt' },
    dayShort: ['Sön', 'Mån', 'Tis', 'Ons', 'Tor', 'Fre', 'Lör'],
    speeds: { fast: 'Snabb', gentle: 'Lugn', authentic: 'Äkta' },
    transitions: { classic: 'Klassisk', wave: 'Våg', drift: 'Drift', curtain: 'Ridå' },
    layouts: { full: 'Hel', header: 'Rubrik och text', split: 'Delad', ticker: 'Löprad', stacked: 'Staplad' },
    zoneNames: { full: ['Hela tavlan'], header: ['Rubrikrad', 'Text'], split: ['Vänster', 'Höger'], ticker: ['Text', 'Löprad'], stacked: ['Övre halvan', 'Nedre halvan'] },
    channels: { message: 'Meddelande', clock: 'Klocka och datum', bigclock: 'Stor klocka', bigtext: 'Stor text', countdown: 'Nedräkning', sl: 'SL-avgångar', weather: 'Väder', art: 'Färgmönster', quote: 'Citat',
      rotating: 'Växlande meddelanden', menu: 'Meny', wordclock: 'Ordklocka', today: 'Idag', electricity: 'Elpris', currency: 'Valuta', onthisday: 'Den här dagen', url: 'Följ en URL', letterclock: 'Bokstavsklocka' },
    colour: 'Färg', rainbow: 'Regnbåge', themeColour: 'Tema', pattern: 'Mönster', every: 'Byt var', seconds: 's',
    patterns: { rainbow: 'Regnbåge', nordic: 'Nordiska flaggor', rain: 'Regn', confetti: 'Konfetti', wave: 'Våg', checker: 'Rutor' },
    view: 'Visa', views: { now: 'Nu', hours: 'Kommande timmar', days: 'Tre dagar' },
    versionLog: 'Versionslogg', back: 'Tillbaka', logNote: 'Varje version är en release, den senaste först. Samma logg finns på', bigTextLabel: 'Text', bigTextNote: 'Stora bokstäver är 5 blad höga, så en 6 x 22-tavla rymmer ungefär 5 tecken åt gången; längre text bläddras ord för ord.',
    slHome: 'Följ min hemstation på SL-kartan', slHomeNone: 'Stjärnmärk en station på SL-kartan för att använda den här.', slHomeIs: name => `Hemstation: ${name}`,
    slMapLink: 'Öppna SL-kartan', slWhat: 'Alla hållplatser i Storstockholms Lokaltrafik (SL): tunnelbana, pendeltåg, spårvagn, buss och båt.',
    volume: 'Volym', soundStyle: 'Bladljud', sounds: { clack: 'Klack', heavy: 'Tungt', soft: 'Mjukt', tick: 'Tick' }, preview: 'Förhandsvisa', previewSound: 'Spela prov',
    templates: 'Börja från en mall', useTemplate: 'Skapa', kioskLink: 'Länk för en väggskärm (kioskläge, inga kontroller)',
    previewing: name => name,
    imported: 'Storyboarden öppnades från en länk.', importFail: 'Filen är inte en storyboard.', linkFail: 'Länken till storyboarden är trasig eller ofullständig.',
    jsonNote: 'JSON betyder JavaScript Object Notation: en textkopia av en storyboard som du kan spara eller flytta till en annan webbläsare.',
    chip: name => `Infoga ${name} färgbricka`, typeOnBoard: 'Skriv på tavlan', duration: 'Tid i sekunder',
    moveUp: 'Flytta upp', moveDown: 'Flytta ned', lang: 'Språk', langHint: 'För redigeraren och för det tavlorna skriver, som dagar och månader. Sparas i den här webbläsaren.', controls: 'Kontroller', editor: 'Redigerare',
    boardLink: 'Länk till storyboarden',
    addTime: 'Lägg till en tid till', removeTime: 'Ta bort den här tiden', rolls: 'Rullningar', rollStart: 'Rulla alla blad när skärmen startar', rollHourly: 'Rulla igen varje hel timme', pageTransition: 'Övergång till den här tavlan', boardDefault: name => `Storyboardens (${name.toLowerCase()})`, showAlone: 'Visa ensam medan den är på', showAloneHint: 'Tavlor utan tid väntar tills den är slut.', winDays: 'Veckodagar', winDate: 'Ett datum', everyYear: 'Varje år',
    monthShort: ['jan', 'feb', 'mars', 'apr', 'maj', 'juni', 'juli', 'aug', 'sep', 'okt', 'nov', 'dec'],
    accSignedOut: 'Utloggad. Logga in för att synka', signInToSync: 'Logga in för att synka',
    accSignedOutBody: n => (n ? `Du loggades ut, så ${n === 1 ? 'en ändring här har' : n + ' storyboards här har ändringar som'} inte nått ditt konto än. ` : 'Du loggades ut. ') + 'Dina storyboards finns kvar här. Logga in igen för att synka dem.',
    confirmSignOutUnsynced: n => `${n === 1 ? '1 storyboard har ändringar' : n + ' storyboards har ändringar'} som inte nått ditt konto än. Anslut och försök igen, eller logga ut ändå och behåll ${n === 1 ? 'den' : 'dem'} här som gäst.`,
    signOutAnyway: 'Logga ut ändå', signOutAgain: 'Tryck igen för att logga ut', deleteAgain: 'Tryck igen för att radera',
    keptAsGuest: n => `Utloggad. ${n === 1 ? '1 storyboard med osynkade ändringar finns' : n + ' storyboards med osynkade ändringar finns'} kvar här som gäst.`,
    refusedBoard: (name, why) => `”${name}” finns bara här: ${why === 'too_many_boards' ? 'ditt konto har 50 storyboards, så många det rymmer.' : why === 'too_big' ? 'den är för stor att spara.' : 'kontot kunde inte ta emot den.'}`,
    signIn: 'Logga in', renameBoard: 'Byt namn på storyboarden',
    account: 'Konto', accGuestSub: 'Gäst, storyboards bara i den här webbläsaren', changedAt: at => `Ändrad ${at}`, accSynced: 'Synkad', accSyncedExcept: n => `Synkad, utom ${n === 1 ? '1 storyboard' : n + ' storyboards'}`, accWaiting: 'Väntar på att synka', accFailed: 'Kunde inte synka, försöker igen',
    accGuestBody: 'Du använder Split-Flap som gäst. Dina storyboards sparas bara i den här webbläsaren, så om du rensar den eller byter telefon eller dator försvinner de.',
    accSignInBody: 'Logga in med Google så sparas dina storyboards med ditt konto, på alla enheter där du loggar in.', signInGoogle: 'Logga in med Google', accPrivacy: 'Vad ett konto sparar',
    offerTitle: n => n === 1 ? 'Det finns 1 storyboard i den här webbläsaren från innan du loggade in.' : `Det finns ${n} storyboards i den här webbläsaren från innan du loggade in.`,
    offerBody: n => n === 1 ? 'Spara den med ditt konto, eller låt den ligga kvar här som den är.' : 'Bocka ur de du vill låta ligga kvar här som de är. Resten går till ditt konto.', offerKeep: 'Spara med mitt konto', offerLeave: n => n === 1 ? 'Låt ligga kvar' : 'Låt alla ligga kvar',
    offerDone: (n, m = 0) => { const a = n === 1 ? '1 storyboard' : `${n} storyboards`, b = m === 1 ? '1 tavla från Mina tavlor' : `${m} tavlor från Mina tavlor`; return `${n && m ? `${a} och ${b}` : n ? a : b} finns nu i ditt konto.`; },
    signInPrompt: safari => 'Dina storyboards finns bara i den här webbläsaren. Logga in så är de säkra och finns på dina andra enheter.' + (safari ? ' Safari rensar dessutom en webbplats lagring efter 7 dagar utan besök.' : ''), notNow: 'Inte nu',
    exportAll: 'Exportera mitt konto', signOut: 'Logga ut', confirmSignOut: 'Dina storyboards tas bort från den här webbläsaren och finns kvar i ditt konto.',
    deleteAccount: 'Radera kontot', confirmDelete: 'Det raderar ditt konto och alla storyboards i det, och det går inte att ångra.', otherDevice: ' (kopia)',
    signInFailed: 'Inloggningen startade inte. Försök igen om en stund.', accountDeleted: 'Ditt konto och dess storyboards är raderade.', signInAgainToDelete: 'Logga in igen av säkerhetsskäl och radera sedan kontot.',
    deleteFailed: 'Kontot kunde inte raderas. Försök igen om en stund.', startGuest: 'Som gäst sparas dina storyboards bara i den här webbläsaren.', syncFailedMark: 'Kunde inte synka',
    help: 'Hjälp', helpSub: 'Så fungerar Split-Flap', gridIs: (r, c) => `Skärmen är ${r} × ${c} flappar.`, changeSize: 'Ändra storleken',
    chooseContent: 'Välj innehåll',
    startTitle: 'Börja från en mall', skip: 'Behåll demostoryboarden',
    moveNamed: name => `Flytta ${name}`, reorderHint: 'Dra för att ändra ordning, eller markera handtaget och använd piltangenterna',
    boardsCount: n => n === 1 ? '1 tavla' : `${n} tavlor`, templatesCount: n => `${n} mallar`, pagesCount: n => n === 1 ? '1 tavla' : `${n} tavlor`,
    pageName: 'Tavlans namn', zones: 'Zoner', tapZone: 'Tryck på en zon för att välja vad den visar.', tapZoneOne: 'Tryck på zonen för att välja vad den visar.',
    showFor: 'Visa i', daysLabel: 'Dagar', from: 'Från', saveImage: 'Spara som bild', less: 'Mindre', more1: 'Mer',
    change: 'Byt', moreOptions: 'Fler alternativ', fewer: 'Färre alternativ', searchContent: 'Sök innehåll',
    shapeNote: (h, w) => `Förhandsvisningarna ritas i zonens form: ${h} × ${w} flappar.`, later: 'Kommer med reläet', noResults: 'Inget matchar. Prova ett kortare ord.',
    remove: 'Ta bort', changeCity: 'Sök efter en annan stad', searchCity: 'Sök efter en stad', addStation: 'Lägg till station', maxStations: 'Högst sex stationer.',
    lineTemplate: 'Radmall', insert: 'Infoga', firstItem: 'Första posten i flödet', sampleFeed: 'Ett exempelflöde, tills du lägger till en adress', prints: 'Tavlan skriver',
    feedErr: 'Adressen gick inte att läsa. Den kanske inte låter andra webbplatser läsa den.', loadingFeed: 'Hämtar flödet.',
    unknownToken: k => `”${k}” finns inte i flödet och skrivs inte ut.`,
    sunFrom: city => `Soltider för ${city}, tavlans plats.`, sunNeedsLoc: 'Soltider behöver en plats. Välj en under', boardName: 'Storyboardens namn',
    boardLoc: 'Plats', locHint: 'Används för soltider och för väderzoner som inte har en egen stad.',
    current: 'Nuvarande', open: 'Öppna', exportB: 'Exportera', importB: 'Importera en storyboard',
    undo: 'Ångra', redo: 'Gör om', composerMode: 'Redigeringsläge', type: 'Skriv', paint: 'Måla', photo: 'Foto',
    brush: 'Pensel', fillTool: 'Fyll', mirror: 'Spegla', paintColour: 'Målarfärg', blankChip: 'Tom',
    choosePhoto: 'Välj foto', takePhoto: 'Ta foto', sampleImage: 'Inget foto valt', sampleNote: 'Välj ett foto eller ta ett. Reglagen placerar det sedan i zonen.',
    photoFail: 'Filen gick inte att öppna som bild.', photoLocal: 'Fotot stannar i den här webbläsaren. Bara flapparna sparas.',
    zoom: 'Zoom', posX: 'Vågrät position', posY: 'Lodrät position', dither: 'Rastrering', ditherHint: 'Blandar flappar för att antyda mellanfärgerna', blankColour: 'Räkna tomma flappar som en färg',
    today: 'Idag', yesterday: 'Igår', drafts: 'Tidigare meddelanden', draftsNote: 'Sparas i den här webbläsaren. Ett meddelande sparas här när du lämnar redigeraren efter en ändring.', noDrafts: 'Inget ännu. Ett meddelande sparas här när du lämnar redigeraren efter en ändring.', use: 'Använd',
  }
};
